### ISSUE TITLE
claim_list should return uniform data structure

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#1006]
`claim_list` currently returns a different data signature based on what type of claim it is (channel vs. stream).

`claim_xxx` API functions promise that they return claims. Claims must have a singular, uniform definition. Fields that are not shared across claim types should either be returned as null or these values should be in a sub-property (e.g. claims could contain `stream` and `channel` sub-properties that contain either null or a map of type-specific properties).

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by lyoshenka** [comment]
part of https://github.com/orgs/lbryio/projects/5

**Comment by eukreign** [comment]
All of the local commands (which query sqlite db) return uniform data structure for tx and txos. Only exception right now is data coming from lbryumx. Re-assigning this to @shyba for further consideration.

**Comment by shyba** [comment]
If I understood it correctly, this relates closely to #1483 but I think it has a broader scope. The issue with missing claim data is being handled at 1483, but maybe we can say this issue is to make the response of `claim_xxx` commands fixed on a template right?

**Comment by tzarebczan** [comment]
It's consistent between channels/claims now, but not consistent with other api commands that hit the wallet server. This will be covered by https://github.com/lbryio/lbry-sdk/issues/2259
