### ISSUE TITLE
Claims returned by jsonrpc responses should include the height of the original claim

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#1042]
Resolving a name returns the height of the latest update to the winning claim for that name, not the height of the original claim. But takeover calculations are based on the height of the original claim. That information needs to be made available by the daemon. 

Example:
```
./lbrynet-cli resolve what
{
  "what": {
    "claim": {
      "address": "bT6wc54qiUUYt34HQF9wnW8b2o2yQTXf2S",
      "amount": 1.999088,
      "claim_id": "6769855a9aa43b67086f9ff3c1a5bacb5698a27a",
      "claim_sequence": 5,
      "decoded_claim": true,
      "depth": 33237,
      "effective_amount": 1.999088,
      "has_signature": false,
      "height": 274108,
      "hex": "080110011adc010801129401080410011a0d57686174206973204c4252593f223057686174206973204c4252593f20416e20696e74726f64756374696f6e207769746820416c6578205461626172726f6b2a0c53616d75656c20427279616e32084c42525920696e6338004a2f68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f66696c65732e6c6272792e696f2f6c6f676f2e706e6752005a001a41080110011a30d5169241150022f996fa7cd6a9a1c421937276a3275eb912790bd07ba7aec1fac5fd45431d226b8fb402691e79aeb24b2209766964656f2f6d7034",
      "name": "what",
      "nout": 0,
      "supports": [],
      "txid": "6c71c02c4990ce0590f6888a77ad11f1ae45486f6a4c56d5013954ee8f6356bc",
      "value": {
        "claimType": "streamType",
        "stream": {
          "metadata": {
            "author": "Samuel Bryan",
            "description": "What is LBRY? An introduction with Alex Tabarrok",
            "language": "en",
            "license": "LBRY inc",
            "licenseUrl": "",
            "nsfw": false,
            "preview": "",
            "thumbnail": "https://s3.amazonaws.com/files.lbry.io/logo.png",
            "title": "What is LBRY?",
            "version": "_0_1_0"
          },
          "source": {
            "contentType": "video/mp4",
            "source": "d5169241150022f996fa7cd6a9a1c421937276a3275eb912790bd07ba7aec1fac5fd45431d226b8fb402691e79aeb24b",
            "sourceType": "lbry_sd_hash",
            "version": "_0_0_1"
          },
          "version": "_0_0_1"
        },
        "version": "_0_0_1"
      }
    }
  }
}
```

This should be amended to include two additional return fields:

- `root_height` : The block height of the original claim.
- `takeover_height`: The block height at which this claim takes effect. If the claim is in effect, `takeover_height` will always be less than `height`.

**Comment by lyoshenka** [comment]
Alternatively, lbrynet should return takeover height information for claims.

**Comment by tzarebczan** [comment]
For your 2nd comment, would https://github.com/lbryio/lbry/issues/1031 be enough?

**Comment by alyssaoc** [comment]
@tzarebczan please confirm that claim take over use original claim height

**Comment by tzarebczan** [comment]
@lyoshenka I did confirm that claim updates don't reset the takeover period. 

However, I'm still skeptical why we need the root height. Isn't it invalid once the claim is taken over? Any takeovers at the vanity URL are then based on the new vanity takeover height. If that's abandoned and it goes back to the original claim, the root_height would no longer be used in the calculation, it would be the takeover_height (when it went back into effect). 

We should be able to get all this info from the blockchain layer.

**Comment by lyoshenka** [comment]
The goal was to be able to show (e.g. in the app) how long it will be before a claim you just made will become the winning claim. So if there's a longstanding claim with multiple updates to it, there's no way to tell how long the takeover process will take.

**Comment by alyssaoc** [comment]
@lyoshenka Can this issue be closed or defined into an actionable issue?

**Comment by lyoshenka** [comment]
The real issue is what I said above:

> The goal was to be able to show (e.g. in the app) how long it will be before a claim you just made will become the winning claim. So if there's a longstanding claim with multiple updates to it, there's no way to tell how long the takeover process will take.

We can either turn this into that, or open it as a new issue. Up to you.

**Comment by tzarebczan** [comment]
This is now shown in the meta section on resolve: 
```
meta": {
        "activation_height": 307232,
        "claims_in_channel": 1109,
        "creation_height": 303200,
```
