### ISSUE TITLE
Improve install instructions

### ISSUE THREAD

**Issue by lbrydocs** [lbryio/lbry-sdk#1106]
I am working on documentation for installs of the main pieces of the LBRY system. I use the following environment for testing:

Lubuntu 16.04.3 LTS - Ubuntu derived, takes half the disk space due to graphics diet.
apt update/apt upgrade so it's current.
tmux - share screens and log activity to text file, so I can watch a developer do an install.

When I run the install for lbry it builds smoothly, but at the end it's clear the person who wrote the instructions is intimately familiar with virtualenv, but not everyone is. I think this needs to be a subsection with a brief explanation of what virtualenv does and more explicit instructions.

The second issue I see is that this software can be run on a headless server, but there is no lbry.service file installed in /etc/systemd/system/, nor is there an example in the ~/lbry directory.

These are issues I can probably correct on my own, but I think it means that in addition to the documentation change there would be a lbry.service file to be included in the repository.

I'm D. Ray Blanco on Discord, would be delighted to get a little bit of time from the person who wrote the existing docs so we can make this smooth.

**Comment by lyoshenka** [comment]
Here's a lbry.service file that would work:

```
[Unit]
Description="LBRY daemon"
After=network.target

[Service]
ExecStart=/path/to/lbrynet-daemon
Restart=on-failure
KillMode=process

[Install]
WantedBy=multi-user.target
```

**Comment by alyssaoc** [comment]
@eukreign Do we want to add any of the above to the install instructions?

**Comment by eukreign** [comment]
I don't think end-users should be using `pip` and `virtualenvs` to install `lbrynet`; especially now that we have on-push builds for all three platforms hosted at http://build.lbry.io/

We should add instructions and sample configs for how to run lbrynet in headless mode on at least Debian/Ubuntu (or common flavor there of).

**Comment by eukreign** [comment]
The scope of this issue should be to create a debian package which properly sets up `lbrynet` to run as a service on Debian / Ubuntu.

**Comment by Ladiesoftheweb** [comment]
> 
> 
> I am working on documentation for installs of the main pieces of the LBRY system. I use the following environment for testing:
> 
> Lubuntu 16.04.3 LTS - Ubuntu derived, takes half the disk space due to graphics diet.
> apt update/apt upgrade so it's current.
> tmux - share screens and log activity to text file, so I can watch a developer do an install.
> 
> When I run the install for lbry it builds smoothly, but it's clear at the end that the person who wrote the instructions is partial to virtualenv, beacause most of us arent familiar with virtualenv, I think this needs to be a subsection with a brief explanation of what virtualenv does and include more explicit instructions.
> 
> The second issue I see is that the software can be run on a headless server, but there is no lbry.service file installed in /etc/systemd/system/, nor is there an example in the ~/lbry directory.
> 
> These are issues I can probably correct on my own, but I think it means that in addition to the documentation change there would be a lbry.service file to be included in the repository.
> 
> I'm D. Ray Blanco on Discord, would be delighted to get a little bit of time from the person who wrote the existing docs so we can make this smooth.

**Comment by tzarebczan** [comment]
These are now up to date for installing the sdk.
