### ISSUE TITLE
Prevent publishing claims with channel_name if not confirmed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#1188]
## The Issue
Based on the findings in https://github.com/lbryio/lbryum-server/issues/53#issuecomment-386394083, we should disallow publishing via the channel_name parameter if the channel name is not confirmed in a block. The documentation should also be updated to reflect this and to recommend using channel_id instead. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by alyssaoc** [comment]
@tzarebczan please check behavior with the new wallet

**Comment by eukreign** [comment]
this was fixed, please reopen if not.
