### ISSUE TITLE
Add `added_at` and `claim_updated_at` columns to the file_list output

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry-sdk#1228]
`added_at` would represent the time the file was added to the database. 

`claim_updated_at` will be added by fixing #2086, which will add the associated Claim object to each file, and the Claim object has a `timestamp` field.

After adding these fields to the database they'd be added as filters to the `file_x` api calls as well.

steps:
- [ ] write migration to add `added_at` column to the sqlite db
- [ ] add code to set `added_at` field for new files
- [ ] fix #2086 
- [ ] add API params for filtering and sorting by these fields

**Comment by eukreign** [comment]
@jackrobison is this still valid / needed with the new async stuff?

**Comment by osilkin98** [comment]
When/if dumping the `ManagedStream` object into JSON, should `added_at` be formatted into a humanly-readable timestamp, or left as is?

**Comment by osilkin98** [comment]
Also is `claim_updated_at` something we're still looking to add?
