### ISSUE TITLE
Some daemon error responses do not contain any failure information (e.g. `wallet_encrypt` with an empty password returns `false`)

### ISSUE THREAD

**Issue by skhameneh** [lbryio/lbry-sdk#1307]
## The Issue

Some error messages do not contain any helpful information.

### Steps to reproduce
1. Call `wallet_encrypt` with an empty password

### Expected behaviour
1. TBD - Responses should ideally contain some categorization of error responses.

### Actual behaviour
`false` is returned, applications and/or user must guess/assume what caused the failure.

## System Configuration

 

App | 0.22.2
Daemon (lbrynet) | 0.20.3
Wallet (lbryum) | 3.2.3

## Anything Else
A common failure response format for all calls would be ideal.

e.g. (purely example)
```
{
  success: false,
  error_type: "PASSWORD_LENGTH"
}
```

**Comment by tzarebczan** [comment]
This is no longer an issue.
