### ISSUE TITLE
Value of a claim is not documented

### ISSUE THREAD

**Issue by 42degrees** [lbryio/lbry-sdk#1472]
## The Issue
When calling "claim_list_mine" and other APIs one of the properties is called "value" with a type of string and a description of "value of the claim".  However, value is not a string, it's actually a (dict) with several properties of its own.  None of these are documented anywhere I could find.  Here is the definition as it looks to me:

{
    "claim_type": (string) The type of the claim, options are "streamType", [what others]
    "publisherSignature": (dict) The signature of the claim (also not documented)
    "stream": (dict) Information about the claim's stream (also not documented) including metadata and source which are both (dict).
}

I think that the documentation should really define these structures separately, rather than trying to define them as part of the API documentation.  The API would then be documented as returning a list of type X, without having to specify the contents of type X (it would point to the documentation for X).  

Therefore "claim_list_mine" and "claim_list" documentation could be simplified to this:

> List my name claims
> 
>         Usage:
>             claim_list_mine
> 
>         Options:
>             None
> 
>         Returns:
>             (list) List of Claims owned by user
>         See: 
>             Claim [linked to documentation for structure Claim]
>

**Comment by tzarebczan** [comment]
Value is now documented in the examples on lbry.tech
