### ISSUE TITLE
"amount" is returned as a number in several places

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-sdk#1576]
## The Issue
`amount` is returned as a number in several places when resolving a claim:
- `claim.amount`
- `claim.supports[x].amount`
- `value.stream.metadata.fee.amount`

<img width="656" alt="screen shot 2018-11-01 at 9 20 24 am" src="https://user-images.githubusercontent.com/16882830/47854271-b4fc7e00-ddb7-11e8-82d9-08923e67fb3e.png">

### Expected behaviour
All lbc amounts should be returned as strings

### Actual behaviour
Only some are

## System Configuration

 

- LBRY Daemon version: 0.30.1rc1
- LBRY App version: 0.26.0rc2
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
We should look into this for the next RC so that the desktop App and other applications can transform all amount values right now instead of doing only some now and some at a future date.

**Comment by tzarebczan** [comment]
This was fixed in https://github.com/lbryio/lbry/pull/1685

**Comment by tzarebczan** [comment]
This is still not a string in fee:
```        "fee": {
          "address": "bStfffg7F2xMaP3Kay35ZaRMe4jqth8t7i",
          "amount": 2.0,
          "currency": "USD"
        },
```

**Comment by tzarebczan** [comment]
This is now complete: 
``` "value": {
      "fee": {
        "address": "bJcz9bmE2BwMPY6BGmPSB7gPeNtEgUJtQY",
        "amount": "0.1",
        "currency": "LBC"
      },
      "languages": [```
