### ISSUE TITLE
Feature request: method to retrieve the latest content from a list of channels

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-sdk#1578]
This is an idea for how subscriptions could improve in the app. Currently we call the first page of videos for every channel a user is subscribed to. If a user has a lot of subscriptions, we fetch a lot of content.

It would be really helpful if you could retrieve the latest 50 files from a list of channels, similar to how the youtube subscriptions page works.

## The Issue

In order to develop a robust subscriptions experience, 
as a developer, 
I want to fetch the latest files from a list of channels.

### Use case
```
Subscribed to channel1, channel2, channel3

channel1 & channel2 post content regularly
channel3 hasn't posted content in a while

currently displayed in subscriptions:
10 files from channel1 (1st file was posted today, 10th file was posted 1 month ago)
10 files from channel2 (1st file was posted yesterday, 10th file was posted 3 weeks ago)
10 files from channel3 (1st file was posted 1 month ago, 10th file was posted 10 months ago)

Desired feature
Call some method `xxx_latest` which returns paginated results where the first page consists of channe1, and channel2 and the second page consists of channel1, channel2, channel3

The user doesn't care about channel3 if their latest file was posted 1 month ago

```

**Comment by tzarebczan** [comment]
This is now possible with claim search
