### ISSUE TITLE
spv server: fix for getclaimsfortx on spent txs

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry-sdk#1581]
Implement a test reproducing this issue and port this previously unmerged PR: https://github.com/lbryio/lbryumx/pull/21

**Comment by tzarebczan** [comment]
@eukreign is this still a valid issue? Do we want users to be able to look up claim data on spent txs?

**Comment by shyba** [comment]
IMO we can close, we dont use this anymore. We fetch and decode
