### ISSUE TITLE
New blockhash argument for lbrycrd RPC commands

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry-sdk#1582]
@kaykurokawa commented on [Wed Oct 24 2018](https://github.com/lbryio/lbryumx/issues/23)

There will now be an optional new blockhash argument for the below lbrycrd RPC commands once this PR is merged https://github.com/lbryio/lbrycrd/pull/189 :

getvalueforname
getclaimsforname
getclaimsintrie
getclaimtrie
getnameproof

This solves the problem where lbryumx must make multiple calls to lbrycrd with the assumption that lbrycrd is maintaining a consistent claimtrie state. However, lbrycrd may have incremented the block in the mean time, making this assumption false. By passing the same blockhash as an argument to these functions, consistent claimtrie state can be maintained.

**Comment by eukreign** [comment]
@shyba are we using this in wallet server?

**Comment by shyba** [comment]
@eukreign it is, but needs to go through planning as its not super easy.

**Comment by tzarebczan** [comment]
spv server now uses its own database, this ticket is no longer valid.
