### ISSUE TITLE
spv server: Make sure race conditions are fixed

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry-sdk#1589]
@shyba commented on [Tue May 15 2018](https://github.com/lbryio/lbryumx/issues/2)

Related to: https://github.com/lbryio/lbryum-server/pull/30
Requires: https://github.com/lbryio/lbrycrd/issues/130

Problem:
While doing large queries over electrum servers, a new block can be detected and processed. This causes race conditions where one query occurs at one height while others at another height, giving inconsistent results.

Changes:
1. lbrycrd RPC commands will return which height the query was made, so we can use that to either retry or inform the client
2. all local queries should be made against the disk, while processing new blocks occurs in memory. We need to ensure that behavior on our custom part of the protocol.

**Comment by alyssaoc** [comment]
#1582 related to

**Comment by tzarebczan** [comment]
This should no longer be an issue with the new SPV server, closing.
