### ISSUE TITLE
spv server: Add address to supports response

### ISSUE THREAD

**Issue by shyba** [lbryio/lbry-sdk#1590]
Related to: https://github.com/lbryio/lbrycrd/issues/92

Changes:
1. keep track of supports address
2. modify the JSON response, include address on supports listing

(2) requires changing the client and could potentially make old clients incompatible. So, the very first step is getting an agreement on what will be the new response format and how to handle old clients.

**Comment by tzarebczan** [comment]
This will be implemented by way of support metadata + new support apis
