### ISSUE TITLE
Add pagination to file_list RPC command

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#1650]
`file_list` results should be paginated, just like other `*_list` RPC commands. 

Might be blocked by https://github.com/lbryio/lbry/issues/1228.

**Comment by tzarebczan** [comment]
This would still be really nice, at least a very crude version based on rowid. All the other apis have pagination. We'll need better support from created at / updated at when it comes with: https://github.com/lbryio/lbry/issues/1228

**Comment by shyba** [comment]
Add `page` and `page_size` parameters, return `total_pages`, `total_items`, `page` and `items`. Probably use or adapt function `maybe_paginate`.
