### ISSUE TITLE
Add more granular balances

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#1706]
## The Issue

The app team would like to show users more information (https://github.com/lbryio/lbry-desktop/issues/617) about their LBC locked up in claims/channels/supports and tipping history. 

Scenarios:
1) Show total LBC used in my own claims, not including supports I sent.
2) Show total LBC used in supports (that I can revoke)
3) Show total LBC sent in tips
4) Show total LBC tipped at a particular claim id/URL
5) Show total LBC received in support of my claims

Some of these may make sense as new api commands or to parameterize account_balance / transaction list.  

## Proposal

Update `account_balance` to return a dictionary with the following fields:

```
{
`total`: all LBC in my wallet
`reserved`: {
  `total`: total LBC in claimtrie
  `claims`:  LBC in claims
  `supports`:  LBC in supports
}
`available`: total_balance minus reserved total (this is what `account_balance` returns now)
`tips_sent`: total LBC sent in tips
`tips_received`: total LBC received in tips of my claims
}
```

This proposal does **not** handle showing total LBC tipped at a particular claim id/URL. If that is still desired, it needs to be discussed further.

**Comment by lyoshenka** [comment]
closed by #2350
