### ISSUE TITLE
Ability to leave comments along with supports/tips

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#1737]
Users want to be able to tip a piece of content and leave a comment with is. Currently comments are made on to an external service. We need to decide if this happens all on the comment create step, or if it's a support create, get txid, and then comment create with it. When calling comment list, the client needs to validate any comments with a txid and make sure that txid is signed by the same channel as the comment. 

If we don't want to do the validation at comment list client side, the server side can do it for now, but that includes a trust factor which is harder to enforce when others run comment servers.

Commentron would require support to track the txid + amount

Flow 1 (1 call)
1) Comment create would take an amount value and create the support create with the same channel as the commentor
2) Comment list would validate any comments with a txid and make sure that txid is signed by the same channel as the comment. If not, don't show comment.

Flow 2 (2 calls)
1) App calls support create with channel id of commenter, grabs txid
2) App passes txid and amount to comment create as part of a new parameters
3) Comment list would validate any comments with a txid and make sure that txid is signed by the same channel as the comment. If not, don't show comment.

**Comment by lyoshenka** [comment]
this is going through comment server
