### ISSUE TITLE
Clearer verbose instructions

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#1739]
## The Issue
When running lbrynet, there are no instructions on how to run verbose mode. To run it correctly, it needs to be executed as: `lbrynet start --verbose=lbrynet`. Is the lbrynet part required? What are other options there?  At a minimum, this should be included in the lbrynet help / lbrynet response. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by mirgee** [comment]
@tzarebczan Currently, the `--verbose` param does not behave as per doc - it is not possible to change the loglevel for any other module than whole lbrynet (setting it to anything changes it to lbrynet) and not setting value does not change loglevel at all. What we should do is probably to make lbrynet the default (when `--verbose` is set), and allow used to select a (proper) module?

**Comment by tzarebczan** [comment]
@shyba do you have an opinion here? I like lbrynet as default - even that's not clear today. Then we can create a separate issue to allow tracking/configuration of certain modules

**Comment by shyba** [comment]
yes, we broke that at some point and I didn't realize. Thanks for the issue!
@tzarebczan agree too. I think `--verbose` should make it all go to DEBUG, so when we dont have something specific we can still see it all there. The selective verbose is very helpful too, since some modules are very noisy and sometimes we are investigating logs only under a specific module.
