### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#1785]
Presumably to lbrysdk.

- [ ] rename the repo
- [ ] update https://github.com/lbryio/boardbot
- [ ] update https://github.com/lbryio/lbry-desktop/blob/master/package.json#L141
- [ ] what else?

**Comment by eukreign** [comment]
Definitely support this and it's on my personal TODO list towards the top. It would be helpful to know all of the places which point to this repo: renaming it is easy, fixing all of the places that point to it is harder.

**Comment by tzarebczan** [comment]
I can help out when needed also. The old url and api calls will auto redirect in most cases.

**Comment by lyoshenka** [comment]
this feels like it creates a bunch of work for no gain. whats the benefit?

**Comment by eukreign** [comment]
For me the primary motivations would be:
1. Calling it what it it is: LBRY SDK. Having SDK in the name like that signals that we really want people to build on it, this is front and center.
2. `lbry` as repo name implies that the entirety of LBRY is in there and while it is definitely a mono-repo for most Python code in LBRY it's still missing the blockchain part (`lbrycrd`) which is a core part of LBRY. Without that core part I don't think it's fair to call it `lbry`.
3. I would like to eventually rename the main Python module from `lbrynet` to just `lbry` and while it's mostly okay to have `../lbry/lbry/..` directory structure (unless you give it a different name when git cloning) this can sometimes cause difficult to debug issues with configuration / import paths. Lot's of projects do this though (repo name == module name), so it's not a big issue, but if we can address the edge case, why not?

Downsides are:
1. potentially creates a bunch of work
2. may have zero impact on actually getting more users

**Comment by eukreign** [comment]
@lyoshenka can we go ahead with the rename?

**Comment by lyoshenka** [comment]
@eukreign i'm ambivalent. if this is valuable and worth doing in the next month, just do it. otherwise close it?

**Comment by kauffj** [comment]
I'm very in favor of doing this unless there are costs I'm not appreciating.

**Comment by eukreign** [comment]
repo renamed to `lbry-sdk`
