### ISSUE TITLE
Consider moving install_id file or generating differently

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#1787]
## The Issue

The install id should be specific to a system, and if the lbrynet folder is moved between different OSes/machines, the install id should be reset/regenerated. When modeling this data on the api (app users), we decided not to allow the system attributes to change (i.e win to linux, or android to mac), and therefore get errors when this occurs.

**Comment by tiger5226** [comment]
This is causing steady errors on internal-apis see https://github.com/lbryio/internal-apis/issues/726

**Comment by lyoshenka** [comment]
internal-apis worked around this
