### ISSUE TITLE
ability to change account password 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#1843]
## The Issue
Currently, there is no way to change an account password without first decrypting it, and then re-encrypting. We should allow a new API call that takes an existing password (if account is locked) and a new encryption password.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
@tzarebczan can't you unlock it with the existing password and encrypt with the new password

**Comment by tzarebczan** [comment]
Nope, you'd need to decrypt it, which leaves it vulnerable on the file system during that time. This was more of a concern for encrypting wallets on LBRY web or other shared sdk instances (assuming wallets can be made in an encrypted state to start off).

**Comment by tzarebczan** [comment]
This part is now possible - you can call wallet encrypt while it's unlocked to encrypt with a new password.
