### ISSUE TITLE
Additional parameters for channel/claim/stream/support/transaction, others? (filter/sort)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#1853]
## The Issue
I should be able to pass parameters like claim id/name, transaction id, channel name, etc to calls like claim_list_mine, channel_list and transaction _list (there may be others too, please do a full scan when grooming). Will will allow us to do things like showing your own tips on a claim, and calling claim_list_mine with a recently publish id to see if it's confirmed, etc. 

This should also include sorting parameters to match the claim search API

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
@tzarebczan do you mean to filter?

**Comment by tzarebczan** [comment]
The app has to work around not having this ability by calling entire claim lists (page size 9999). This would make things like checking if you have a publish at a URL much simpler.

**Comment by seanyesmunt** [comment]
This would help lbry.tv a lot because currently we need to fetch every one of the users claims to see if they have reposted something before.

It would be nice to pass the name when they navigate to the file page and get info just for that name

**Comment by tzarebczan** [comment]
Overall, the goal is to give these local API calls more robust apis similar to claim search where you can filter and sort. 

This is my first pass as to what would be required at a minimum so that the app can get away from calling large page lists, and the 2nd section would be the fuller picture/nice to have. 

Note: Do we need to support "no_totals" like we do in claim search for performance reasons, or because it's local / smaller data it should be fine? 

Required:
**Claim list** 
filter by: claim_id (list), txid + nout (list)

** Transaction list** - 
filter by: is_tip, claim_id (list), txid + nout (list), type (list) [claim, abandon, support, update], 

** Support list** (we won't have to call this if https://github.com/lbryio/lbry-sdk/issues/2841 is done) 
Add field: is_tip - we have a type field - maybe we can use that instead?
filter by: is_tip, claim_id (list), txid+nout (list)

Nice to have:
**Channel list**  (we use this now, but we could use claim list + claim type = channel - but this would make the apis consistent at least)
filter by: claim_id (list), txid + nout (list)

**Stream list** (not currently being used by app, we are using claim list + claim_type - but this would make the apis consistent at least). 
filter by: claim_id (list), txid + nout (list)

Across all the apis, be able to pass similar parameters as claim search - this means various order by options and attributes like:
name
channel
channel_ids
has channel signature
invalid channel signature
is controlling
height
timestamp
creation_height
release_time
amount
support_amount
trending *
reposted_claim_id
reposted
claim types
stream types
media_types
fee_amount
duration
any_tags
any_languages
any_locations

**Comment by tzarebczan** [comment]
Re-opening this as txo list is missing outgoing transactions.  Need to re-check that filters match similar to what we have in the app currently: 
![Screenshot_20200307-004603](https://user-images.githubusercontent.com/8120721/76793111-d5ee2500-679a-11ea-98cc-c2869151e804.jpg)


Also, we'd need https://github.com/lbryio/lbry-sdk/issues/2853 to be added as well to fully switch over.
