### ISSUE TITLE
Capture architecture with system data

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#1856]
## The Issue
We want to know how many people are running 32 vs 64 bit oses. Sounds like the best place to capture this would be on the daemon (and analytics), and then the app can pass it to our apis. 

Some suggestions here: https://stackoverflow.com/questions/2764356/python-get-windows-os-version-and-architecture/16657852#16657852 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
might be in app analytics

**Comment by tzarebczan** [comment]
We want to capture on sdk side...to see how many sdk users run 32 bit so we can eventually move to 64. This would be passed up to the app along with other stats we are already collecting.

**Comment by tzarebczan** [comment]
We are no longer supporting 32bit in official builds
