### ISSUE TITLE
Optimize videos for quickstart (moov atom)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#1988]
## The Issue
https://pypi.org/project/qtfaststart/

Add an additional parameter to publish  (default off?) which allows optimizations, such as the one above, to run automatically (this could be one of many). This ensures that the video (h264/quicktime) can start playing as soon as it writes the first bytes. Some video players have trouble otherwise, and will require the whole video to be downloaded. 

Need to consider if we overwrite the user's original file, or create a new one (create + delete?)? What if it's a large file and there's no enough space? 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
While testing out range requests, unoptimized files generally cause more issues (can't stream in some browsers) and require additional blobs (last 3/4) to be downloaded before you can start playing. We should make this an optional parameter on publish/stream create calls to optimize mp4s automatically. 

Do we need to modify the user's local file when doing so or can it be done on the fly?

**Comment by tzarebczan** [comment]
We are still having trouble with manually uploaded files that are not web optimized on lbry.tv and these also take longer to stream since it needs to download the last blob.

**Comment by lyoshenka** [comment]
@BrannonKing this is related to what you're working on

**Comment by BrannonKing** [comment]
Addressed with https://github.com/lbryio/lbry-sdk/pull/2726
