### ISSUE TITLE
Incorrect claim id length while resolving with short claim id

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lbry-sdk#1991]
The resolve command needs to support short claim id as these will be used when resolving canonical urls.
This blocks #958

**Comment by tzarebczan** [comment]
You mean 958 blocks this right?  We don't have short IDs, so how can you resolve them :)

**Comment by hackrush01** [comment]
Maybe.
What I mean is that, this has to be added before and/or parallely to #958

**Comment by tzarebczan** [comment]
I'd assume that work would be done with 958, otherwise it's pretty useless by itself.

**Comment by hackrush01** [comment]
Yes. This is just to keep track I guess.

**Comment by tzarebczan** [comment]
This is now fixed
