### ISSUE TITLE
Support for re-posting content to channel

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2028]
## The Issue
Implement an API where users can re-post a claim to their own channel. Optimally, this would be done via support metadata (to own address). This will require new types/protobufs to be created (https://github.com/lbryio/types/issues/32).  Using supports alleviates the need to create a new claim (and claim namespace) to be created. 

Considerations:
Reposts would return with channel claims, have a special identifier. 
Does it make sense to re-post anonymously? 
What fields do we allow to be set with a repost? 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
I think this issue should be strongly considered as a next feature addition. It would simultaneously be a useful feature AND advance censorship resistance, as we can use the re-posting feature to allow wallet servers to know about which content is reported as a DMCA (or other) violation in a decentralized way.

**Comment by tzarebczan** [comment]
Closing this since the basic API is complete.
