### ISSUE TITLE
Make resolve even faster and less CPU intensive

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2030]
## The Issue
Resolving claims is very CPU intensive and slow, especially in the case where multiple claims are being resolved at once. While stress testing the sdk with resolving hundreds of claims at a time, we noticed that each subsequent resolve was slower. This would also affect the speed of other calls to the SDK (i.e. get / claim search).  On lbry.tv under heavy usage, the docker image takes up tons of memory and eventually stops responding. 

There's also a high IO wait when the SDK goes under this heavy load, possibly waiting for requests to return from the wallet server. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by sayplastic** [comment]
I think we should also make it [less sequential when handling multiple requests](https://gist.github.com/sayplastic/5264e74b9275901ab9bcc8fa16034530)

**Comment by tzarebczan** [comment]
This has been implemented
