### ISSUE TITLE
claim_search updates for discovery

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#2072]
To support the discovery changes outlined in the https://github.com/lbryio/growth/issues/207 epic, `claim_search` must support the following parameters:

(all parameter names are suggestions, or in the case of some particularly bad ones, not even that :)

- `tag` (1 or more strings) - only return claims with this tag
- `published_since` - only return claims created since this block height (or date, if possible)
- `sort` (`publish_date_desc`, `publish_date_asc`, `release_date_asc`, `release_date_desc`, `trending_effective_amount`, `absolute_effective_amount`)
- `effective_amount_window` - the window to consider absolute and trending amounts over. For example, a value of 2 weeks combined with a sort of `absolute_effective_amount` would return the claims that had the highest effective_amount increase over the last 2 weeks. This parameter is used only for trending and/or absolute effective amount searches.

**Comment by kauffj** [comment]
![IMG_20190410_120211](https://user-images.githubusercontent.com/530774/57022154-47150000-6bfc-11e9-949e-eb6796e93e25.jpg)
![IMG_20190410_120205](https://user-images.githubusercontent.com/530774/57022159-48462d00-6bfc-11e9-9009-f52e25b3a564.jpg)

**Comment by kauffj** [comment]
@seanyesmunt see anything I missed here?

**Comment by tzarebczan** [comment]
@eukreign - add ability to pass multiple channels to claim search, and return paginated/sorted results across the entire list. This would work with the parameters for search / published since as specified in the OP.

**Comment by tzarebczan** [comment]
This has been implemented. Please file new issues for any missing functionality.
