### ISSUE TITLE
pass file list data through json encoder

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2086]
The claim objects in the response from `file_list` are missing some fields like `permanent_url`. Jack says this is prolly a bug with the Claim json encoder.

claim_address and permanent_url are inconsistent in claim subfield of file vs claim results.

**Comment by shyba** [comment]
The goal is to have the output of file_list and claim_list consistent on claim fields (file is associated to a claim so it needs to show the claim information as expected from other claim commands)

**Comment by lyoshenka** [comment]
fixed in #2447
