### ISSUE TITLE
merge torba into master

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#2096]
Our current setup is a mono-repo of all our python code, except torba. Torba is installed using a pypi dependency. When work happens simultaneously in torba and lbry, its easy for them to get out of sync and cause install/update problems. Putting them in the same repo eliminates that problem, obviates the need to put extra instructions into install.md, and puts all our code in one place (completing the mono-repo vision).

**Comment by eukreign** [comment]
`torba` merged into `lbry-sdk`
