### ISSUE TITLE
Pagination does not have a default page_size thus doesn't work

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-sdk#2097]
## The Issue
Paginated endpoints don't return paginated results is page_size is not passed

### Steps to reproduce
1. call claim_list with --page=1 and no --page_size
2. ??
3. profit

### Expected behaviour
```
{
  "items": [
...
  ],
  "page": 1,
  "page_size": 50,
  "total_pages": 1
}

```
### Actual behaviour
```
[
...
]
```

## System Configuration

latest master on linux

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Oleg was working on file list pagination, this is for claim *

**Comment by f1x3d** [comment]
@tzarebczan may i take this one?

**Comment by tzarebczan** [comment]
@f1x3d please do!
