### ISSUE TITLE
Tag API Endpoint(s)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#2099]
While we'll be able to launch new tag-based discovery features without this functionality, the SDK presumably ought to facilitate app-side tagging functionality and discovery in the future.

Something like a `tag_search` for finding tags that match criteria (e.g. search by name, order by popularity) could be used by both publishing and discovering tags to follow.

This ticket should be researched and discussed with @lbryio/appsquad before proceeding.

**Comment by tzarebczan** [comment]
this was completed as part of claim search. I'll open a new ticket for a specific tag based api to get tag analytics
