### ISSUE TITLE
content blocking in wallet server

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#2110]
- wallet server should have a configurable way of identifying blocked claims
	- information to block on: claim id, sd hash, and file hash.
	- simple but less-ideal solution: enter a URL that returns a JSON of blocked claim ids
	- better solution: something that uses the protocol itself (maybe a configurable channel to follow where publishes to that channel identify blocked claims). 
		- new claim type: blocked content
			```
			{
				operation: add|remove,
				report_id: 866192843, # id of the report we received that prompted us to block this content
				claim_ids: ["2349a999b32","abc123",...],
			}
			```
			
		- when you set up what channel is blocked, you must pin it to a claim id so you don't worry about the name being taken over. 
		- try to do anything we can to minimize the ways the blocklist can change
- update `resolve` and `search` wallet server methods to return information about blocked claims. the information should include 
	- the number of results that were blocked
	- how to find out more about why those results were blocked

## Q&A

- if a claim is blocked, can we still return the raw tx that contains that claim? the raw transaction may be necessary for downstream services. my guess is this is fine, but we need to check
	- we're taking the position that raw transactions are fine.
- how do we handle the case where the winning claim is blocked but there are other claims for that name? do you return the second winning claim, or a blocked error?
	- return a blocked error
- what if the first-place claim gets abandoned and the second-place claim is blocked?
	- its now blocked
- more generally, what if you look up all claims for a name? do you hide the blocked claims from that list? how do you explain how to find out more about the blocked claims?
- not returning claims can cause validation issues. if claims cant be returned, you may not be able to validate the claimtrie structure. in lbrycrd we should be safe because it does not know about metadata.
- what happens if you spend a banned claim into a new claim for the same name with the same metadata? what if you do something similar but slightly more obfuscated (spend two banned claims into two new claims that swap the names and metadata)?
- maybe its not a banned list, but a "only this channel has the rights to this stream hash" list?
- what if you were gonna publish to a name that already had a claim that was blocked? for example, what would the app say is the minimum takeover amount necessary?
- can a whole channel be blocked?

**Comment by shyba** [comment]
From Jeremy on Slack (about the API changes here):

```
 - Instead of a single list of channels to look at for filtering, allow a list-of-list structures that looks something like this:
{
  dmca : [@lbryincdmca#abc, @sonyincdmca#def]
  malicious: [@lbryincmalicious#abc, @mcaffeemalicious#123]
}
- For xxx_list calls, instead of a count_blocked property, return a filtered property that looks something like this:
...
filtered: {
  total: 50,
  dmca: 20,
  malicious: 30
  ...
}
- Ideally, allow these configuration values to be updated dynamically without a full restart of the server, but this isn't strictly necessary for a v1

(flexible on exact structures, names, etc. this is just a sketch, not an exact prescription)
```

**Comment by lyoshenka** [comment]
re Jeremy's idea:

we like it. we're gonna do it as a next step after v1 is done.

---

we're also considering client-side filtering in addition to server-side:

# client-side filtering (for the future)
- add `--filtering-channels=` flag to claim_search so client can add additional filtering channels to the search
- also allow filtering out single claims?
- performance issues? what if you add 10 giant filtering channels? does that make the query slow?

**Comment by lyoshenka** [comment]
farther down the line, we'd like a nice UI for wallet server operators to see/add/remove what channels are blocked

**Comment by lyoshenka** [comment]
blocked by https://github.com/lbryio/lbry-sdk/issues/2666

**Comment by lyoshenka** [comment]
im gonna say this is done. if there's outstanding stuff, please open specific issues @eukreign
