### ISSUE TITLE
make header download fast enough that we can stop hosting them on s3

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#2112]
Right now we get blocks in chunks of 2000. Elecrumx is a line-based protocol, and having more than 2k blocks on a single line causes issues.

We can create a new api method for fast header sync that uses protobuf or grpc instead of stratum.

done when:
- downloading headers from wallet server is (roughly) as fast as downloading from S3
- s3 header download is dropped completely
- s3 header upload script is disabled (or this is filed for later if there are upgrade/migration issues for older daemon versions)

**Comment by shyba** [comment]
we can quickly experiment with base64 + higher chunk sizes before we have a complete revamp of the protocol

**Comment by shyba** [comment]
2488 was merged
