### ISSUE TITLE
update search method to use external search provider (aka lighthouse)

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#2118]
the `blockchain.claimtrie.search` method in the wallet is pretty basic. there are many robust search solutions such as Elasticsearch that are way better. the wallet server should offload search functionality to these solutions when possible.

- document an api between wallet server and search provider
- pass `search` requests along to provider. pass responses back to client. 
- robust search is optional. if it is not available, fall back to existing search.

**Comment by tzarebczan** [comment]
More info in : https://github.com/lbryio/lbry-sdk/issues/2023

**Comment by lyoshenka** [comment]
search is hubs uses Elastic now
