### ISSUE TITLE
profile and speed up file_list on windows when you have several hundred files

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#2144]

**Comment by tzarebczan** [comment]
I also had this prevent a successful upgrade on my machine because the SDK would not shutdown. This is because the file_list call is blocking on startup and when run, the SDK does not close.

**Comment by tzarebczan** [comment]
See https://github.com/lbryio/lbry/issues/1975 for some timings I did a while ago. Had a user run it with 7K files and it took about 2 minutes.

**Comment by lyoshenka** [comment]
> file_list call is blocking on startup and when run, the SDK does not close.

this should not happen anymore since the recent shutdown fix

**Comment by lyoshenka** [comment]
closed by #2384
