### ISSUE TITLE
0.38 mega issue

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2172]
Will continue to add more as we find em: 
- [x] BLOCKER: `claims in channel` count does not update after claim abandoned. The below should say 0. 
(lbry-venv) C:\Users\thoma\Documents\lbry>lbrynet resolve @testcount6-10
```{
  "@testcount6-10": {
    "address": "bUkTwEodXSWPMcKTazUEB9RuH2gdxP3QZx",
      "claims_in_channel": 1,
```
- [x] BLOCKER: Victor will fix publish/stream update with sending blank fee address. 

- [x] ~~BLOCKING: make sure queries are non blocking~~

- [x] not a blocker but quick and easy: claim search should normalize queries on tags. Possibly normalize when storing too. 

- [x] BLOCKER: claim search on abandoned channel should be handled better. You also get something similar if claim_ids is not passed as a list. 
```
(lbry-venv) C:\Users\thoma\Documents\lbry>lbrynet claim search --channel=@thumbnails#4355959afd7e79a48729ed9f438eb02fff38f5f8
{
  "code": -32500,
  "data": [
    "Traceback (most recent call last):",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbrynet\\extras\\daemon\\Daemon.py\", line 576, in _process_rpc_call",
    "    result = await result",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbrynet\\extras\\daemon\\Daemon.py\", line 1798, in jsonrpc_claim_search",
    "    txos, offset, total = await self.ledger.claim_search(**kwargs)",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbrynet\\wallet\\ledger.py\", line 78, in claim_search",
    "    return await self._inflate_outputs(self.network.claim_search(**kwargs))",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbrynet\\wallet\\ledger.py\", line 57, in _inflate_outputs",
    "    outputs = Outputs.from_base64(await query)",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbry-venv\\lib\\site-packages\\torba\\client\\basenetwork.py\", line 32, in send_request",
    "    raise e",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbry-venv\\lib\\site-packages\\torba\\client\\basenetwork.py\", line 29, in send_request",
    "    return await super().send_request(method, args)",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbry-venv\\lib\\site-packages\\torba\\rpc\\session.py\", line 481, in send_request",
    "    raise result",
    "torba.rpc.jsonrpc.RPCError: (-32603, 'internal server error')",
    ""
  ],
  "message": "(-32603, 'internal server error')
```

**TOM'S WISH LIST:**
- [x] (nice to have as we missed it): add ability to filter by key fee + index.
- [x] add last takeover height to resolve/claim list
- [x] ~~remove  is_change / is_mine from resolve /claim search response. "is_change": false,  "is_mine": false,~~

- [ ] canonical/short url should be added to local claim commands like claim/stream/channel list. This would need to hit the wallet server unless we had a workaround. Otherwise resolve/claim search commands are not consistent in their return with local wallet commands. 

- [ ] handle bad inputs on claim search, i.e. `lbrynet claim search --stream_types="boo"`
```{
  "code": -32500,
  "data": [
    "Traceback (most recent call last):",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbrynet\\extras\\daemon\\Daemon.py\", line 576, in _process_rpc_call",
    "    result = await result",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbrynet\\extras\\daemon\\Daemon.py\", line 1816, in jsonrpc_claim_search",
    "    txos, offset, total = await self.ledger.claim_search(**kwargs)",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbrynet\\wallet\\ledger.py\", line 78, in claim_search",
    "    return await self._inflate_outputs(self.network.claim_search(**kwargs))",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbrynet\\wallet\\ledger.py\", line 57, in _inflate_outputs",
    "    outputs = Outputs.from_base64(await query)",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbry-venv\\lib\\site-packages\\torba\\client\\basenetwork.py\", line 31, in send_request",
    "    raise e",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbry-venv\\lib\\site-packages\\torba\\client\\basenetwork.py\", line 28, in send_request",
    "    return await super().send_request(method, args)",
    "  File \"c:\\users\\thoma\\documents\\lbry\\lbry-venv\\lib\\site-packages\\torba\\rpc\\session.py\", line 481, in send_request",
    "    raise result",
    "torba.rpc.jsonrpc.RPCError: (-32603, 'internal server error')",
    ""
  ],
  "message": "(-32603, 'internal server error')"
```

- [ ] add a filter for "evaluation period" - this would take into account any supports/effective amount changes in the last X amount of time. This would allow us to do a "hot" section by sorting by effective amount over last X period of time.  This is different from the claim creation/update time.  Could we also do this with another trending period? 

- [ ] add some way to multiply claim trending scores by channel effective amount (i.e. if channel has a large effective amount [relative to others?], boost the trending score)? Should should be done via a param. Then we can show a view that's called something like "trending on popular channels".  

- [ ] some way to return bottom half, or bottom 80% from a result of claim search. This could allow us to do something like a "up and coming category" where it hasn't reached the top 20% of trending, but we want to show it to get some attention. If not, how else can we do something similar. 

- [ ] figure out why this is happening: https://github.com/lbryio/lbry/issues/2152 (has not been happening on 0.38 - leave for now.)

- [ ] ttfb script broken (jack)

- [x] BLOCKER show stream_type based on media_type for legacy content (not updated to new metadata). Also, show stream_type: "other" when it's not one of the known types. 

- [x] BLOCKER: When updating a claim using publish + fees, the fee address is lost (0.37 bug).  There are probably some claims around with this and they will fail on download. Can we work around that by using claim address if fee address is not set? 

```      "value": {
        "fee": {
          "amount": "0.5",
          "currency": "LBC"
        },
```
```
c:\Program Files\LBRY\resources\static\daemon>lbrynet get testfee-528
{
  "error": "invalid literal for int() with base 16: b''"
}
```

- [x] BLOCKER?: activation height seems wrong on resolve five: `activation_height": 531717,` Height is `"height": 570482` - I can see how activation can happen earlier if the claim was updated / other claims removed, but lbrycrd shows : `"nLastTakeoverHeight": 572150` . How's this calculated? 

- [x] BLOCKER: if a channel is abandoned and it has signed claims, those claims will no longer tell you that the signature is invalid or that it had a channel previously. I think it used to show the channel and show invalid signature. I think it would be good for the publisher to still see this, and we'd show invalid/them them fix it..otherwise they won't even know which channel it belonged to. 
- [x] BLOCKER: Need a way to identify a certificate from the wallet to a channel. Before it was uxto so it was easy, but now it's a public key hash that's not shown anywhere else. Maybe we can just add this to the channel metadata as the publish key hash.
- [x] BLOCKER: --is_valid_signatures param breaks claim search (on channel id too)
- [x] BLOCKER: add media type and value type (claim/channel) to claim search filtering params. 
- [x] Some claims like lbry://z don't return a value (they do in 0.37). The below should resolve to 877923215bfa82aba7be051af5cebaa037076e15
```(lbry-venv) C:\Users\thoma\Documents\lbry>lbrynet resolve z
{
  "z": {
    "address": "bMHxmT2UDuhXznqE4vZ4wou3QSAoLY1sWw",
    "amount": "0.1",
    "claim_id": "93bb17d66272a7fad520abe9d16991b4497775e6",
    "claim_op": "create",
    "confirmations": 561621,
    "height": 10798,
    "meta": {
      "activation_height": 10798,
      "claims_in_channel": 0,
      "effective_amount": "0.1",
      "is_controlling": true,
      "support_amount": "0.0",
      "trending_global": 0.0,
      "trending_group": 0,
      "trending_local": 0.0,
      "trending_mixed": 0.0
    },
    "name": "z",
    "normalized": "z",
    "nout": 1,
    "permanent_url": "lbry://z#93bb17d66272a7fad520abe9d16991b4497775e6",
    "timestamp": 1468353037,
    "txid": "26ce711e29ad681a7a8290564f3202e17c2eb72b4b5f820327883df5105303e9",
    "type": "claim"
  }
}
```

---

---

---
- [x] *_urls should use non-normalized names. 
- [x] claim search not working by channel or claim id. (no result)
- [x] claim search very slow when searching by tags with  `oder_by="effective_amount"`, or something like ```lbrynet claim search --order_by=effective_amount``` which shows top of all time.
- [x] claim search should take multiple channels as input and return results sorted across those channels. 
- [x] claims in channel shown for in claim meta - suppress it? We did have this in resolve before for claims, but it doesn't make sense. 
- [x] check for presence of `signing_channel` field to see if it's signed, check for presence of `value` field  to see if a claim could be decoded ~~missing in resolve from 0.37: has_signature (maybe not important as long as is_channel_signature is present/correct), valid at height (is this the same as activation height?), decoded claim (we need some way to tell if the claim can be decoded).~~

- [x] for signed claims, should the signing channel have the same meta section as claim does (do we track trending for channels?)?  Since we no longer show the certificate, we need the effective amount for the signing channel, and valid at height (if this is the same as activation height, then maybe we do want meta to solve these). 

- [x] how do we show supports on resolve? Are we adding optional ones in this release?

- [x] normalized -> normalized_name? 

- [x] claim search should return total items in results

- [x] `claim['height']` is last updated, `claim['meta']['creation_height']` is when it was created ~~block height vs publish time is confusing. We talked about changing it to timestamp, but that's still confusing because it doesn't tell you that this is the updated timestamp. Not sure what the resolution is.~~

- [x] `claim['timestamp']` is last updated, `claim['meta']['creation_timestamp']` is when it was created ~~add created_timestamp / keep timestamp updated when claim updates happen. Jeremy didn't like the naming, same reason as above.~~

**Comment by osilkin98** [comment]
The `claim search` method is completely broken, giving it any input besides help results in the following output:

```js
(lbry-venv) oleg@t420:~/PycharmProjects/comment-server$ lbrynet claim search --channel="@otter"
{
  "code": -32500,
  "data": [
    "Traceback (most recent call last):",
    "  File \"/home/oleg/PycharmProjects/lbry/lbrynet/extras/daemon/Daemon.py\", line 576, in _process_rpc_call",
    "    result = await result",
    "  File \"/home/oleg/PycharmProjects/lbry/lbrynet/extras/daemon/Daemon.py\", line 1798, in jsonrpc_claim_search",
    "    txos, offset, total = await self.ledger.claim_search(**kwargs)",
    "  File \"/home/oleg/PycharmProjects/lbry/lbrynet/wallet/ledger.py\", line 78, in claim_search",
    "    return await self._inflate_outputs(self.network.claim_search(**kwargs))",
    "  File \"/home/oleg/PycharmProjects/lbry/lbrynet/wallet/ledger.py\", line 57, in _inflate_outputs",
    "    outputs = Outputs.from_base64(await query)",
    "  File \"/home/oleg/PycharmProjects/lbry/lbry-venv/lib/python3.7/site-packages/torba/client/basenetwork.py\", line 32, in send_request",
    "    raise e",
    "  File \"/home/oleg/PycharmProjects/lbry/lbry-venv/lib/python3.7/site-packages/torba/client/basenetwork.py\", line 29, in send_request",
    "    return await super().send_request(method, args)",
    "  File \"/home/oleg/PycharmProjects/lbry/lbry-venv/lib/python3.7/site-packages/torba/rpc/session.py\", line 481, in send_request",
    "    raise result",
    "torba.rpc.jsonrpc.RPCError: (-32601, 'unknown method \"blockchain.claimtrie.search\"')",
    ""
  ],
  "message": "(-32601, 'unknown method \"blockchain.claimtrie.search\"')"
}
```

**Comment by osilkin98** [comment]
This appears to exist in the `resolve` command as well, and I'm going to assume any other claimtrie related torba code. I'd make an issue in `torba` but it feels like it belongs here.

**Comment by eukreign** [comment]
all of the issues that will go into 38 are done; the rest should go into separate issues for future releases
