### ISSUE TITLE
handle reorgs on wallet server

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#2185]
### punchlist

- [x] get to the point where the server doesn't crash when a reorg happens. don't worry about correctness, just make it not crash first.
- [ ] something else

### ideas

- sqlite snapshots (https://www.sqlite.org/undoredo.html, https://www.reddit.com/r/sqlite/comments/aapon0/looking_for_snapshot_and_restore_functionality_in/)
- copy less things (just claimid, activation height, is_channel_sig_valid) and see how much space that takes up
- before every query, run a select that does the same thing but records a list of records returned

**Comment by tzarebczan** [comment]
This is still an issue in the claims table during a re-org. 
```   "message": "(1, 'tx hash a06c1bbce4b120f4a07d71aa715354e02a54affd5564a2f9e2016de7d10329ce not in block 58d4907924dd1e9bd9df05a48ef5ebb09e8f03987e3d822f8172108d05950d22 at height 738,075')"```
