### ISSUE TITLE
Check address validity before sending

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2235]
## The Issue
We don't do any basic address verification when sending credits, but instead someone may end up sending coins to an invalid address. We should try to do something similar to what LBRYcrd does here: https://github.com/lbryio/lbrycrd/blob/7f6daef99b06d6fd3d56d5e2146fdbf9d1b0187b/src/key_io.cpp#L73

For example, if I try to send to `bDr3bMzpCGtpwnxayP8KdwXe37WvnXaKKS` (1 character off from bDr3bMzpCGtpwnxayP8KdwXe36WvnXaKKS) which is an invalid address according to lbrycrd, the transaction goes to `bDr3bMzpCGtpwnxayP8KdwXe37Wvk1Nk6z` https://explorer.lbry.com/address/bDr3bMzpCGtpwnxayP8KdwXe37Wvk1Nk6z 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by lyoshenka** [comment]
the rpc call where this happened was wallet_send
