### ISSUE TITLE
Faster daemon startup for mobile use case

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#2237]
Over the last 9,000 new users that launched the LBRY mobile app, 4,000 quit the app before the daemon finished launching. Akin says it can take up to 30 seconds for this to happen.

Potential approach: start components in the order that the app needs them during startup. Make the jsonrpc api responsive right away, and defer as much of the slow stuff to later in the startup process.

Related: https://github.com/lbryio/lbry-android/issues/515

**Comment by kauffj** [comment]
@akinwale what are the current stats for this?

> Over the last 9,000 new users that launched the LBRY mobile app, 4,000 quit the app before the daemon finished launching. Akin says it can take up to 30 seconds for this to happen.

**Comment by akinwale** [comment]
@kauffj Missed the notification for this message. We don't depend on the SDK being ready for the app to actually be usable upon startup any longer, so I haven't been tracking this.
