### ISSUE TITLE
Calculated data (canonical / meta)  in local claim APIs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2259]
Breaking out from mega issue:

Canonical/short url and other data in META (i.e. creation time) should be added to local claim commands like claim/stream/channel list if a parameter is passed (Or is it all fast enough to hit the wallet server efficiently now?). 

This would need to hit the wallet server unless we had a workaround. Otherwise resolve/claim search commands are not consistent in their return with local wallet commands. 

This is important for the app because we'd need to resolve all published content to show the dates/urls.

**Comment by seanyesmunt** [comment]
This is important to have. 

We currently can't show the publish time on the "your publishes" page without resolving every single publish since claim list doesn't return the creation_timestamp
