### ISSUE TITLE
Don't show fee section if amount is 0 or currency/address don't exist

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2270]
If you publish a claim with fee=0.0, we show the fee address but the claim can't be downloaded. We should probably not allow fee amount of 0, or any combination that doesn't lead to a fee address/amount/currency. 

I know we have some old claims like this too, we should fix this up if it's an easy one. 

```
2019-06-26 21:00:23,930 WARNING  lbrynet.extras.daemon.Daemon:937: Error downloading lbry://CityLifeRPGLivestream3May2019at172220190627011118: must be real number, not NoneType
```

**Comment by osilkin98** [comment]
This one seems to have already been fixed, passing a bid of 0 yields the message: 
`"message": "Invalid value for 'bid': 'bid' value must be greater than 0.0"`
