### ISSUE TITLE
Improve wallet/transaction sync speed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2278]
Syncing many transactions is slow in 0.38, like 2/3 times slower than previous versions. See spee.ch wallet or some yt sync wallets. @shyba aware of this.

**Comment by tzarebczan** [comment]
I want to say it's gotten slower in this version too, in combination with https://github.com/lbryio/lbry-sdk/issues/2266

**Comment by eukreign** [comment]
fixed in #2304
