### ISSUE TITLE
Improve wallet server performance on queries (resolve/claim search) and make non-blocking

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2283]
After @shyba fixed the locking issue, we noticed poor performance on beta.lbry.tv with just a few people hitting the server for queries. The CPU would hit 100% and the pages would take 20+ seconds to load.

**Comment by tzarebczan** [comment]
The server is still currently freezing up every few hours. This is a blocker.

**Comment by lyoshenka** [comment]
closed by #2307
