### ISSUE TITLE
Wallet-server needs description and link to travis logs on docker hub

### ISSUE THREAD

**Issue by EnigmaCurry** [lbryio/lbry-sdk#2288]
There is currently no description or link to build logs for the wallet-server on docker hub - https://hub.docker.com/r/lbry/wallet-server

Ideally there would be a link to the logs of all wallet-server builds. I don't know travis well enough to know if there is a permalink for that or not. But linking to the main page would be good enough: 
https://travis-ci.org/lbryio/lbry-sdk

Also add a link to the project source tree: https://github.com/lbryio/lbry-sdk

Docker hub allows you to free-form edit descriptions, so it does not need to be a README in the git repo, (but it could be)

**Comment by lyoshenka** [comment]
done
