### ISSUE TITLE
completed status and blob completed incorrect in streaming mode

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2293]
streaming `what` on a fresh install with save files/blobs off - completed shows true, and blobs completed shows a value. No blobs exist on disk. 

This is pretty bad for the desktop app streaming solution because we only want to show completed files when they are actually completed - the file is saved, or all the blobs are saved (on disk too). 
```
(lbry-venv) C:\Users\thoma\Documents\lbry>lbrynet file list --claim_name=what
[
  {
    "blobs_completed": 2,
    "blobs_in_stream": 76,
    "blobs_remaining": 74,
    "channel_claim_id": null,
    "channel_name": null,
    "claim_id": "19b9c243bea0c45175e6a6027911abbad53e983e",
    "claim_name": "what",
    "completed": true,
    "confirmations": 208412,
```

**Comment by lyoshenka** [comment]
`completed` is confusing in this mode. if you're not saving files or blobs, is the stream ever actually complete?

after some discussion, the solution is that `completed` will only be true if the file has been written to disk (and that will only happen if saving files is on). `completed` will be completely separate from blobs. if you want to know what's up with blobs, look at `blobs_*` fields.
