### ISSUE TITLE
Use op_return to mark transaction as paid for claim id

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2300]
Until we figure out a path forward for stricter proof of payment, we should consider adding the claim id to a 0 value op_return transaction (has 80 bytes of data available) to identify the purchase for both the seller and buyer. Today, there is only a transaction record for the amount, without any metadata.

**Comment by kauffj** [comment]
If/when this is done, `get` should also use this information rather than the local DB

**Comment by lyoshenka** [comment]
Whoever picks this up: check that OP_RETURN output is not considered non-standard, or if it is, that that doesn't cause problems.

**Comment by shyba** [comment]
0. small prototype code: use torba transaction API to add a custom op_return output
1. check that this approach works quickly (op_return with claim_id broadcasted to a wallet server is seen as standard and ends up in a block) -> same code as a test, it probably is fine, can find clues here: https://github.com/lbryio/lbrycrd/blob/master/src/script/standard.cpp#L132
2. add tests, make it available and call when doing fee payments
3. (maybe another issue) `get`, `file_list` and other APIs should be updated to use that to differentiate payments. Probably updating the json encoder should be enough
