### ISSUE TITLE
Reconnect on wallet server list update

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#2341]
When the list of wallet servers is updated, if the current wallet server is not on that list, disconnect from the current server and do a reconnect. 

In the app, there's only one wallet server at a time. so if that one changes, reconnect. Current sdk behavior requires an sdk restart to reconnect. That's painful.

**Comment by shyba** [comment]
changing means setting the conf through the API

**Comment by tzarebczan** [comment]
This has been implemented with wallet reconnect
