### ISSUE TITLE
update url regex check

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2351]
I mentioned before that the app team decided to disallow a few characters that would normally cause trouble in web urls (including spaces), but we decided to leave the unicode ones. The SDK should match the ```regex: export const regexInvalidURI = /[ =&#:$@%?;/\\"<>%{}|^~[\]`\u{0000}-\u{0008}\u{000b}-\u{000c}\u{000e}-\u{001F}\u{D800}-\u{DFFF}\u{FFFE}-\u{FFFF}]/u;```

**Comment by shyba** [comment]
closed on #2473
