### ISSUE TITLE
Monitoring for wallet server response times

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#2361]
- a script of some sort that listens on websocket and sends data to metabase db
  - handle wallet server restarts
  - notify us (slack, phone call, etc) when wallet server goes down
- show 50%ile and 95%ile response times on graph
- cleanup/summarizing of historic data so the db doesn't get too big
- for each *slow* `resolve` or `claim_search` response, record the query that caused that slowness

talk to Andrey. he's investigating monitoring/graphing tools too

**Comment by eukreign** [comment]
done
