### ISSUE TITLE
Claim search parameter to exclude content without thumbnails

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2364]
Content that's images posted through the app or spee.ch may not have thumbnails, and most users probably won't want to check out content without them. There should be a way to filter these out via claim search.

See https://github.com/lbryio/lbry-desktop/issues/2695 for reference.

**Comment by kauffj** [comment]
How many pieces of content do not have images because no image is set vs. the URL does not return an image?

Also, consider text posts - am I really supposed to set an image for these?

(I agree that there is a good and worthwhile idea here, I just think it needs a little seasoning.)

**Comment by lyoshenka** [comment]
This feels like a pretty narrow use case, and should be handled in the app
