### ISSUE TITLE
Sync/wallet enhancements to support existing synced wallets + multi-account awareness

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2382]
Update: I think the main objective is to have a wallet wide command for encrypting/decrypting across multiple accounts. Unless an account id is passed, we should assume any of these commands would be applied to all accounts. We'd need to run this after sync apply, after checking if any of the accounts are encrypted. If a blank password was used on Android, we could re-encrypt all with the same so they are uniform. If no encryption is used, users would have to option of leaving as it or adding it later. 

*Note:* Keep in mind we have a scenario today on Android where some users will have multiple non-default & blank & unencrypted accounts in their wallet because we don't delete/delay the initial account when clearing data/wallets. This is also now the case on Desktop. On Mobile, we allow a password, on Desktop we do not yet. 

In order to support https://github.com/lbryio/lbry-sdk/issues/2264 for existing sync users, the sync API will need to ensure that a single encryption password is used for all accounts. When a user with an existing synced wallet tries to turn on sync on a new/existing device, we don't have a way of knowing if their passwords are the same until we run a sync apply. If we don't want to handle these scenarios, we'll need to block syncing for users with existing synced wallets (unless their current wallet has a 0 balance or hash matches) and provide a FAQ on how to start over with a single account (this becomes more painful with publishes and channels). We will probably also need https://github.com/lbryio/lbry-sdk/issues/2153 to stop the creation of blank accounts on new devices. 

**Scenario 1:** 
User has an Android wallet with password X (could be blank), and signs into the desktop app which has a non-encrypted wallet. When we prompt the user to enable sync, we'll ask them for an optional password. Knowing that this user has an account, we would try to run sync apply. This should return successfully if either a blank password (to match Android) or password X is used. If not, it should return an appropriate error message. We'd then encrypt all the accounts with the same password. 

**Scenario 2:**
User has an Android wallet with password X (could be blank), and signs into the desktop app which has a wallet also encrypted with a password. We'll allow the user to enable sync, and the sync apply process should complete successfully since passwords match. We'd then want to encrypt all the accounts with the same password.

**Comment by eukreign** [comment]
fixed in https://github.com/lbryio/lbry-sdk/pull/2524
