### ISSUE TITLE
Add extensions bitfield to DHT datagram format

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry-sdk#2391]
Add a bitfield to indicate support for optional extensions as a new keyword argument `x`, defaulting to one byte. A datagram without the extension field defaults all values to False. Schema:

bit 1: TCP supported
    set if the listening port is accepting tcp blob requests

bit 2: UDP transfer requests supported
    set if the node accepts udp transfer requests

bit 3: uTP supported
    set if the node accepts incoming uTP connections

bit 4: detect NAT
    if set, the extension byte will be followed by 2 bytes representing the listening port of the sender. the recipient will reply with this bit set followed by the observed source port from the sender.

bits 5-8: reserved

**Comment by lyoshenka** [comment]
closed by #2552
