### ISSUE TITLE
Wallet server stops sending notification of new blocks

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2392]
Opening this since we don't know the root cause yet, but recently spv1 (and possibly other servers) stopped notifying clients of incoming blocks. This causes any new claim searches to fail with the unpack error. On restart, the client would catch up, but would stop seeing new blocks, which means they were being processed on the server, but not announced. 

This was remedied by restarting the server in the meantime. We'll add client-side monitoring to boris in order to tell immediately when this happens again.

Spv3 is in this boat at the moment.

**Comment by lyoshenka** [comment]
fixed by #2395
