### ISSUE TITLE
Claim search and resolve - does not identify your own claims

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-sdk#2404]
If I search for my channel name it does not show `is_mine` as true. However, if I do a channel list it does.

**Comment by tzarebczan** [comment]
is_mine is not a response for claim search / resolve - it was removed since it wasn't correct. To add it back in, claim search would also need to reference the local wallet data which it does not currently.

**Comment by tzarebczan** [comment]
Related: https://github.com/lbryio/lbry-sdk/issues/1853
