### ISSUE TITLE
Publishing Claims with Identical Names Under Different Channels Fails

### ISSUE THREAD

**Issue by osilkin98** [lbryio/lbry-sdk#2416]
If you published a claim with the name, "NewClaim," doing so again under a different channel will result in a duplicate claim name error.

To allow this, you need to include `--allow_duplicate_name=True`. This should not be the default behavior when the claim is being published under a different channel from the already existing ones.

**Comment by tzarebczan** [comment]
This is the default with the publish command since it assumes a single claim name per wallet so it can do updates properly. The stream create command should let you do this by default.

**Comment by osilkin98** [comment]
@tzarebczan This occurred with the `stream_create` command, I should've been clearer.

**Comment by tzarebczan** [comment]
I'd still say this is the right behavior for now. Otherwise you'll be bidding against yourself on two claim names, regardless of the different channels.
