### ISSUE TITLE
trending/new claim search on a few channels times out (+mature off)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2420]
Claim search + trending/new is failing on just a few channels. Other users are reporting the same. Top works. If I enable mature content (removing the Not tags), it works also. 

```{"jsonrpc":"2.0","method":"claim_search","params":{"page_size":20,"page":1,"no_totals":true,"any_tags":[],"channel_ids":["5a1b164d0a2e7adf1db08d7363ea1cb06c30cd74","e8f68563d242f6ac9784dcbc41dd86c28a9391d6","589276465a23c589801d874f484cc39f307d7ec7","305e682b180d71cc941a40b14ebf799ac974544f","930fc43ca7bae20d4706543e97175d1872b0671f","2305db36455aa0d18571015b9e9bd0950262aa0f","7b1c72ba903af4aecdc2595397a9cb91bb7f188d","feb61536c007cdf4faeeaab4876cb397feaf6b51"],"not_channel_ids":[],"not_tags":["porn","nsfw","mature","xxx"],"order_by":["trending_global","trending_mixed"]},"id":1566867802657}```

**Comment by tzarebczan** [comment]
The above query seems to be working now, but others like `{"jsonrpc":"2.0","method":"claim_search","params":{"page_size":20,"page":1,"no_totals":true,"any_tags":["science"],"channel_ids":[],"not_channel_ids":[],"not_tags":["porn","nsfw","mature","xxx"],"order_by":["effective_amount"],"release_time":">1566941028"},"id":1567545828318}` or the ones recently on [Metabase timeout list](https://traction.lbry.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjM5NywiYnJlYWtvdXQiOltbImZpZWxkLWlkIiwxMzU4M11dLCJhZ2dyZWdhdGlvbiI6W1siY291bnQiXV0sIm9yZGVyLWJ5IjpbWyJkZXNjIixbImFnZ3JlZ2F0aW9uIiwwXV1dLCJsaW1pdCI6MTAwMCwiZmlsdGVyIjpbImFuZCIsWyJ0aW1lLWludGVydmFsIixbImZpZWxkLWlkIiwxMzU4Nl0sLTEsImRheSIse31dXX19LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7InRhYmxlLnBpdm90X2NvbHVtbiI6InF1ZXJ5IiwidGFibGUuY2VsbF9jb2x1bW4iOiJjb3VudCJ9fQ==) don't

It's more concerning that these break randomly...

**Comment by tzarebczan** [comment]
There are still many claim searches failing if you check metabase. In many cases, if you enable mature content (which removes the not tags params), they work. We should look into simplifying that portion of the query somehow.

**Comment by seanyesmunt** [comment]
Forced to add this in lbry-desktop until this is resolved 
https://github.com/lbryio/lbry-desktop/pull/3539/files#diff-b87cd32e151bf117deee7aa96e07774fR113-R116

**Comment by kauffj** [comment]
new SDK expected to fix this but @shyba you could use this ticket as some cases to test
