### ISSUE TITLE
Lower trending window

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2426]
We should consider lowering the trending window from 1 day to at least ~12 hours or potentially even lower so that trending content feels more responsive / changes more often in the app.

**Comment by lyoshenka** [comment]
@kauffj let us know what windows you'd like and we'll see if its still performant

**Comment by tzarebczan** [comment]
We'd like to try a 6-hour window, still over 7 days.

**Comment by lyoshenka** [comment]
fixed in #2484
