### ISSUE TITLE
Invalid canonical url after channel update / claim search returns invalid claim in a blank channel

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2435]
```{"jsonrpc":"2.0","method":"claim_search","params":{"channel":"lbry://@eeeee#e96441129064f9ae0b158876aecc4b66aa87d96e","page":1,"page_size":20,"valid_channel_signature":true,"order_by":["release_time"]},"id":1567175330316}```

returns a claim with ```"canonical_url": "lbry://@aaaaaaaa#3/aaaaaaaaa#f",```

**Comment by tzarebczan** [comment]
This happens when a channel changes on a claim: See this one I recently updated: ```  "\u2652#8": {
    "address": "bYJKJqFftwGCvPbuGvMecxAnANz25X1SRs",
    "amount": "1.0",
    "canonical_url": "lbry://@testnew#2/\u2652#8",
    "claim_id": "86031656165b8288408684472633d8a8915fcae0",
    "claim_op": "update",
    "confirmations": 2,
    "height": 625754,
    "is_channel_signature_valid": true,
    "meta": {
      "activation_height": 594449,
      "creation_height": 594449,
      "creation_timestamp": 1562189499,
      "effective_amount": "1.0",
      "expiration_height": 2696849,
      "is_controlling": true,
      "support_amount": "0.0",
      "take_over_height": 594449,
      "trending_global": 0.0,
      "trending_group": 0,
      "trending_local": 0.0,
      "trending_mixed": 0.0
    },
    "name": "\u2652",
    "normalized_name": "\u2652",
    "nout": 0,
    "permanent_url": "lbry://\u2652#86031656165b8288408684472633d8a8915fcae0",
    "short_url": "lbry://\u2652#8",
    "signing_channel": {
      "address": "bYJ2r5QmGfQjnZWSj2xgwE957sZUgd7GCr",
      "amount": "10.0",
      "canonical_url": "lbry://@LBRY-Tom#c",
      "claim_id": "c474d46ef096084d3eaa58fef6a50b5cfbf8f096",
      "claim_op": "create",```

**Comment by tzarebczan** [comment]
Here's another example that's affecting a user's channel after he updated his claims. This is affecting claims on the homepage/trending

```    "items": [
      {
        "address": "bPp8vuU6SoYek5dLPfuycP5rsihAof9Ej1",
        "amount": "3.0",
        "canonical_url": "lbry://@DreamScape#f/Dreamscape-432-Omega#f",
        "claim_id": "f601d9a5fd7c5031cfcbb49e9869eddbb3f730f7",
        "claim_op": "update",
        "confirmations": 2751,
        "height": 624824,
        "is_channel_signature_valid": true,
        "meta": {
          "activation_height": 618894,
          "creation_height": 618894,
          "creation_timestamp": 1566125648,
          "effective_amount": "128.0",
          "expiration_height": 2721294,
          "is_controlling": true,
          "support_amount": "125.0",
          "take_over_height": 618894,
          "trending_global": 0.0,
          "trending_group": 2,
          "trending_local": 8999999488.0,
          "trending_mixed": 8999999488.0
        },
        "name": "Dreamscape-432-Omega",
        "normalized_name": "dreamscape-432-omega",
        "nout": 0,
        "permanent_url": "lbry://Dreamscape-432-Omega#f601d9a5fd7c5031cfcbb49e9869eddbb3f730f7",
        "short_url": "lbry://Dreamscape-432-Omega#f",
        "signing_channel": {
          "address": "bFBXcdpimeZvHdvcqpMh6h6q6yLXwyjwPE",
          "amount": "25.0",
          "canonical_url": "lbry://@Dreamscape#c",
          "claim_id": "c4dd78bcff002a2ae99e28c883a655f58e106423",
          "claim_op": "update",
          "confirmations": 2987,
          "height": 624588,
          "meta": {
            "activation_height": 618898,
            "claims_in_channel": 1,
            "creation_height": 618894,
            "creation_timestamp": 1566125648,
            "effective_amount": "25.0",
            "expiration_height": 2721294,
            "is_controlling": true,
            "support_amount": "0.0",
            "take_over_height": 618898,
            "trending_global": 0.0,
            "trending_group": 0,
            "trending_local": 0.0,
            "trending_mixed": 0.0
          },
          "name": "@Dreamscape",
          "normalized_name": "@dreamscape",
          "nout": 0,
          "permanent_url": "lbry://@Dreamscape#c4dd78bcff002a2ae99e28c883a655f58e106423",
          "short_url": "lbry://@Dreamscape#c",
          "timestamp": 1567043840,
          "txid": "56ef40f482d449b54d7eb72fe55c2b750e768c0d2f05f9d826dd36b256ad5f3f",
          "type": "claim",
          "value": {
            "cover": {
              "url": "https://spee.ch/0/84ce6f86-a9a0-4285-9a91-bfc1517dfd71.jpg"
            },
            "public_key": "3056301006072a8648ce3d020106052b8104000a0342000493e9c38cd6b0071fd07f98d765d25e3bdeb1a2430b2a353d4c4e7904c71d90371246eb8b5178a06838d92d57fb595505f160725e4aecf8efa4b97b34dc55f49f",
            "public_key_id": "bQL7CNPJ8BQNA8CwhEcxfo9YipDMWGGZ73",
            "tags": [
              "Ambient",
              "Chill",
              "soundscape",
              "music"
            ],
            "thumbnail": {
              "url": "https://spee.ch/d/868b0a2f-9fc1-4290-ba9a-66a8002d0655.png"
            }
          },
          "value_type": "channel"
        },```

**Comment by tzarebczan** [comment]
These are still broke, so it's not a caching issue.

**Comment by danger89** [comment]
But I still suffer properly from this issue. Causing the content not to load. Console only gives: Can't find file viewer wrapper to attach to the inline viewer to.

And sometimes behind the video player, the text: "There's nothing available at this location.".
