### ISSUE TITLE
timed out queries return nonetype error

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2442]
Timed out queries used to return a nice error about timeout. Now we get this on 0.40/Master. Spv1 (0.39.3 works fine and returns results - even more concerning). 

query: ``` {"jsonrpc":"2.0","method":"claim_search","params":{"page_size":20,"page":1,"no_totals":true,"any_tags":[],"channel_ids":["da5534547c15856646c1bd281313ddd55cbec407","f9b1aafbca572b930d1b98038592d5403c66ec84","2f04823d34317bb4f4c9624440667ea614942237","36b7bd81c1f975878da8cfe2960ed819a1c85bb5","f0cb90bbe9ba6cf958a3fc2261a6743997e13551","c145a475a806c7ccce0a81d22e81a88af6ff5c42","3408cd1a6474d3f5ee4ace4737dc36a70b7b13e9","e48d2b50501159034f68d53321f67b8aa5b1d771","c5724e280283cd985186af9a62494aae377daabd","08f31fe3fa6caa14799d7a7d1de8713553f5e8ee","21ec3d11ee55d8a8aae691485d8af982371f4f7b","97dd77c93c9603cbb2583f3589f7f5a6c92baa43","589276465a23c589801d874f484cc39f307d7ec7","f5cd68fc0d2edcde180bee2f6de48fc9cc5ee1f3","f5d33e957beca0ac93d71f37f600050510b983b2","8cda4bb5516c487e85137880b58909ef690b5bba","a0f1f8e50dbc4d104edc5640081a71d19cb98702","f0e3b3fe1adedb556b1356772ed3fd7ad20e16bf","af6a1aa93702eaef7bb7844ba89cbf67f252954f","feb61536c007cdf4faeeaab4876cb397feaf6b51","c9da929d12afe6066acc89eb044b552f0d63782a","2a391f01bc91e8df3a15503c93132bfd28d2c694","7af198a2b0a29aea6c96beef660ac8abcf0afbad","fb364ef587872515f545a5b4b3182b58073f230f"],"not_channel_ids":["3cabf5f5f01c5bc244c96ab20f709b6a7668af5f","e11e2fc3056137948d2cc83fb5ca2ce9b57025ec","6c1119f18fd7a15fc7535fcb9eec3aa22af66b6b","d5557f4c61d6725f1a51141bbee43cdd2576e415"],"not_tags":["porn","nsfw","mature","xxx"],"order_by":["trending_global","trending_mixed"]},"id":1567533760746}```

```{
  "error": {
    "code": -32500,
    "data": [
      "Traceback (most recent call last):",
      "  File \"c:\\users\\thoma\\documents\\lbry\\lbry\\lbry\\extras\\daemon\\Daemon.py\", line 584, in _process_rpc_call",
      "    result = await result",
      "  File \"c:\\users\\thoma\\documents\\lbry\\lbry\\lbry\\extras\\daemon\\Daemon.py\", line 1898, in jsonrpc_claim_search",
      "    txos, offset, total = await self.ledger.claim_search(**kwargs)",
      "  File \"c:\\users\\thoma\\documents\\lbry\\lbry\\lbry\\wallet\\ledger.py\", line 77, in claim_search",
      "    return await self._inflate_outputs(self.network.claim_search(**kwargs))",
      "  File \"c:\\users\\thoma\\documents\\lbry\\lbry\\lbry\\wallet\\ledger.py\", line 56, in _inflate_outputs",
      "    outputs = Outputs.from_base64(await query)",
      "  File \"c:\\users\\thoma\\documents\\lbry\\lbry\\lbry\\schema\\result.py\", line 59, in from_base64",
      "    return cls.from_bytes(base64.b64decode(data))",
      "  File \"C:\\Users\\thoma\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\base64.py\", line 80, in b64decode",
      "    s = _bytes_from_decode_data(s)",
      "  File \"C:\\Users\\thoma\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\base64.py\", line 46, in _bytes_from_decode_data",
      "    \"string, not %r\" % s.__class__.__name__) from None",
      "TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'",
      ""
    ],
    "message": "argument should be a bytes-like object or ASCII string, not 'NoneType'"
  },
  "jsonrpc": "2.0"
}
```

**Comment by jackrobison** [comment]
on lbrynet 0.40.1

```Traceback (most recent call last):
  File "lbry/extras/daemon/Daemon.py", line 584, in _process_rpc_call
  File "lbry/extras/daemon/Daemon.py", line 925, in jsonrpc_resolve
  File "lbry/extras/daemon/Daemon.py", line 3802, in resolve
  File "lbry/wallet/ledger.py", line 63, in resolve
  File "lbry/wallet/ledger.py", line 56, in _inflate_outputs
  File "lbry/schema/result.py", line 59, in from_base64
  File "base64.py", line 80, in b64decode
  File "base64.py", line 46, in _bytes_from_decode_data
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'```

**Comment by tzarebczan** [comment]
Another user ran into while on 0.39.3 wallet servers: 
```Daemon: 2019-10-03 07:54:35,785 ERROR    lbry.extras.daemon.Daemon:590: error handling api request
Traceback (most recent call last):
  File "lbry/extras/daemon/Daemon.py", line 584, in _process_rpc_call
  File "lbry/extras/daemon/Daemon.py", line 2035, in jsonrpc_claim_search
  File "lbry/wallet/ledger.py", line 77, in claim_search
  File "lbry/wallet/ledger.py", line 56, in _inflate_outputs
  File "lbry/schema/result.py", line 59, in from_base64
  File "base64.py", line 80, in b64decode
  File "base64.py", line 46, in _bytes_from_decode_data
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'```

**Comment by jiggytom** [comment]
The above seems to work on master now, will try other queries.

**Comment by tzarebczan** [comment]
Still getting this ugly error (   "TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'",) instead of a timeout. 

Query example: 
```{"jsonrpc":"2.0","method":"claim_search","params":{"page_size":20,"page":1,"no_totals":true,"any_tags":[],"channel_ids":["0956afbfbf7be2232dccf1dc01c4d89dae060220","b8cad60753f066e697afc38d2a27bf0c3c1fd133","81ee31eb59ecfa98d6d4b50a5ab1ac95817daf1b","df8d21cc38add74c0af9cfe721be5b0fc03b4faf","a96f49028e79ca996e284ca83634850ab011949c","20ad9090184d7812970b0ab75e94565b3aec5807","e48d2b50501159034f68d53321f67b8aa5b1d771","c5724e280283cd985186af9a62494aae377daabd","4fa230f864cc4cd9c7d9962c042c49f35e913ffe","f8d6eccd887c9cebd36b1d42aa349279b7f5c3ed","04784caee866e077d46ad9f34a14cc84a289b80c","e8f68563d242f6ac9784dcbc41dd86c28a9391d6","97dd77c93c9603cbb2583f3589f7f5a6c92baa43","589276465a23c589801d874f484cc39f307d7ec7","3e3a8a085105470ad918a8f9975ee6090e2d12c8","ff80e24f41a2d706c70df9779542cba4715216c9","e8fed337dc4ee260f4bcfa6d24ae1e4dd75c2fb3","76ee2fb363855df7e979835ceadcb7d938fe9cd5","9be0244b4bf0e36df678946816d8c9154494ad92","779cd2600cd5c6babe789f6e273910d3c8b28bd3","e50beec197c7d1cd2f9e6ce0f4176fee9d4949b9","c9da929d12afe6066acc89eb044b552f0d63782a","571b35609b90cffceafee38242a6c48f9499c276","fb364ef587872515f545a5b4b3182b58073f230f","e0218ba174c0fb783af24406d22d4c55b4951173"],"not_channel_ids":["35e4135d5d93739004bff6afbec776329fc7d6fa"],"not_tags":["porn","nsfw","mature","xxx"],"order_by":["trending_global","trending_mixed"]},"id":1572382956003}```

it works if I remove the mature not tags.

**Comment by tzarebczan** [comment]
And now it's working again with or without the mature tags. Still concerning.

**Comment by tzarebczan** [comment]
This should be fixed on the latest version
