### ISSUE TITLE
wallet_balance command to show balance for entire wallet

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry-sdk#2516]

**Comment by tzarebczan** [comment]
right now wallet_balance return signature is different from account balance. Is the plan to have account balance return across all accounts also? If not, we'll need to switch calls in the apps too. We are using the granular balances from account balance.

**Comment by tzarebczan** [comment]
Sorry, I was referring to wallet list. We don't have a wallet balance. I think using account balance is fine.

**Comment by eukreign** [comment]
command added in https://github.com/lbryio/lbry-sdk/pull/2533
