### ISSUE TITLE
Use fstrings

### ISSUE THREAD

**Issue by ju-sh** [lbryio/lbry-sdk#2520]
Since the codebase uses Python3.7, can we not fstrings instead of `.format()` where fstrings are more suited?

Since fstrings are usually faster than their `format()`-ed counterparts, let us use fstrings where they do no impair readability.

I would be interested in working on this if this proposal is accepted.

**Comment by eukreign** [comment]
We already use fstrings in most of the code base.

**Comment by ju-sh** [comment]
@eukreign  But there are many still in the repo which can be at least be made more readable with fstrings. Is it intentionally left as such?

**Comment by eukreign** [comment]
you're always welcome to make a small PR and we can discuss from there.

**Comment by ju-sh** [comment]
@eukreign I made a commit using fstrings. Can you have a look?

https://github.com/lbryio/lbry-sdk/pull/2522
