### ISSUE TITLE
adjust behavior of wallet unlock with blank password

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2576]
This is a follow up to https://github.com/lbryio/lbry-sdk/issues/2565 / https://github.com/lbryio/lbry-sdk/pull/2568 which made wallet_unlock '' decrypt the wallet. 

This started happening on the latest SDK, so any Android users who didn't use a password that installed / updated between Friday/Monday would be affected. 

The original purpose was to reset the `encrypt-on-disk` setting which was set to True for the above users when they started up the latest update. 

While in this state (is_locked false / encrypted true, but not actually encrypted), sync hash/sync apply fail because it thinks it's encrypted but has no password.  

Calling wallet_unlock with '' works on Android since we always save the password, but not on other platforms since there is no way to tell if we should really call it because to fix the bug, or if we would call it and decrypt their account by accident (i.e. on lbry.tv, or LBRY desktop where a password is not saved and the SDK is already running). 

This could work if we only call wallet decrypt if the `encrypt-on-disk` setting is on but any of the accounts are not encrypted (i.e. prevent decrypting with wallet unlock if the account is actually encrypted).

**Comment by eukreign** [comment]
fixed in #2577
