### ISSUE TITLE
Add torrent support to SQLiteStorage

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry-sdk#2619]
- [x] add new tables for torrents
- [x] decouple `file` table from `stream` table, entries in `file` can have sources of either torrents or lbry streams
- [x] update `content_claim` table to associate an outpoint to either a stream hash or a bt infohash.
- [ ] add torrent counterpart to `get_all_lbry_files`
- [x] add torrent counterpart to `get_claims_from_stream_hashes`
- [x] add torrent counterpart to `delete_stream`
- [ ] add torrent counterpart to `store_file`
- [x] add db migration script

**Comment by lyoshenka** [comment]
victor says i can close this
