### ISSUE TITLE
antix 19 debian white screen only

### ISSUE THREAD

**Issue by danrobi11** [lbryio/lbry-sdk#2626]
So i just tried to run lbry flatpak and white screen only. Same with the deb file.
lbry 0.37.1
OS: Debian GNU/Linux 10 (buster) x86_64 
Kernel: 4.9.182-antix.1-amd64-smp 
Resolution: 1920x1080 
WM: IceWM 1.5.5+git20190610 (Linux/x86_64) 
WM Theme: Clearview Blue Medium 
Theme: Arc-EvoPro2 [GTK2/3] 
Icons: papirus-antix [GTK2/3] 
Terminal: roxterm 
CPU: Intel i5-3570K (4) @ 3.800GHz 
GPU: Intel HD Graphics 
GPU: NVIDIA GeForce GTX 780 
Memory :  5836MiB / 15931MiB 

$ flatpak run io.lbry.lbry-app
Starting SDK
Sandbox listening on port 5278.
Daemon: 2019-11-17 21:06:06,938 INFO     lbry.extras.daemon.Daemon:402: Starting LBRYNet Daemon

Daemon: 2019-11-17 21:06:06,939 INFO     lbry.extras.daemon.Daemon:404: Platform: {
  "processor": "",
  "python_version": "3.7.1",
  "platform": "Linux-4.9.182-antix.1-amd64-smp-x86_64-with-glibc2.3.4",
  "os_release": "4.9.182-antix.1-amd64-smp",
  "os_system": "Linux",
  "lbrynet_version": "0.43.3",
  "torba_version": "0.5.7",
  "build": "release",
  "distro": {
    "id": "org.freedesktop.platform",
    "version": "19.08.3",
    "version_parts": {
      "major": "19",
      "minor": "08",
      "build_number": "3"
    },
    "like": "",
    "codename": "Flatpak runtime"
  },
  "desktop": "Unknown"
}

Daemon: 2019-11-17 21:06:06,985 INFO     lbry.extras.daemon.Daemon:412: RPC server listening on TCP ::1:5279

Daemon: 2019-11-17 21:06:07,004 INFO     lbry.extras.daemon.Daemon:422: media server listening on TCP ::1:5280

Daemon: 2019-11-17 21:06:07,135 INFO     lbry.extras.daemon.Components:564: detecting external ip

Daemon: 2019-11-17 21:06:07,136 INFO     lbry.extras.daemon.Components:67: Loading databases

Daemon: 2019-11-17 21:06:07,136 INFO     torba.client.basedatabase:233: connecting to database: /home/danrobi/.var/app/io.lbry.lbry-app/data/lbry/lbrynet/lbrynet.sqlite

Daemon: 2019-11-17 21:06:07,137 INFO     lbry.extras.daemon.exchange_rate_manager:213: Starting exchange rate manager

Daemon: 2019-11-17 21:06:07,279 INFO     lbry.extras.daemon.Daemon:388: detected internet connection is working

Daemon: 2019-11-17 21:06:07,283 INFO     lbry.extras.daemon.Daemon:821: Get version info: {"processor": "", "python_version": "3.7.1", "platform": "Linux-4.9.182-antix.1-amd64-smp-x86_64-with-glibc2.3.4", "os_release": "4.9.182-antix.1-amd64-smp", "os_system": "Linux", "lbrynet_version": "0.43.3", "torba_version": "0.5.7", "build": "release", "distro": {"id": "org.freedesktop.platform", "version": "19.08.3", "version_parts": {"major": "19", "minor": "08", "build_number": "3"}, "like": "", "codename": "Flatpak runtime"}, "desktop": "Unknown"}

(node:3) UnhandledPromiseRejectionWarning: Error: Unknown or unsupported transport “disabled” for address “disabled:”
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Daemon: 2019-11-17 21:06:07,350 INFO     lbry.extras.daemon.Components:180: remote height: 664762, local height: 668247

Daemon: 2019-11-17 21:06:07,559 INFO     lbry.extras.daemon.Components:220: Header checkpoint verified.

(lbry-app:3): IBUS-WARNING **: 21:06:09.037: Unable to connect to ibus: Unknown or unsupported transport “disabled” for address “disabled:”
Daemon: 2019-11-17 21:06:23,217 WARNING  lbry.extras.daemon.Components:493: upnp discovery failed: M-SEARCH for 192.168.2.1:1900 timed out

Daemon: 2019-11-17 21:06:23,217 ERROR    lbry.extras.daemon.Components:579: failed to setup upnp

Daemon: 2019-11-17 21:06:23,245 INFO     lbry.extras.daemon.Components:258: Starting torba wallet

Daemon: 2019-11-17 21:06:23,428 INFO     lbry.extras.daemon.Components:336: start the dht

Daemon: 2019-11-17 21:06:23,428 WARNING  lbry.extras.daemon.Components:342: UPnP component failed to get external ip

Daemon: 2019-11-17 21:06:23,430 INFO     torba.client.basedatabase:233: connecting to database: /home/danrobi/.var/app/io.lbry.lbry-app/data/lbry/lbryum/lbc_mainnet/blockchain.db

Daemon: 2019-11-17 21:06:23,540 INFO     torba.client.basenetwork:311: connected to spv1.lbry.com:50001

Daemon: 2019-11-17 21:06:23,541 INFO     torba.client.basenetwork:175: Switching to SPV wallet server: spv1.lbry.com:50001

Daemon: 2019-11-17 21:06:23,541 INFO     torba.client.baseledger:289: Subscribing and updating accounts.

Daemon: 2019-11-17 21:06:23,554 INFO     torba.client.basenetwork:311: connected to spv2.lbry.com:50001

Daemon: 2019-11-17 21:06:23,570 INFO     torba.client.basenetwork:179: Subscribed to headers: spv1.lbry.com:50001

Daemon: 2019-11-17 21:06:23,570 INFO     torba.client.baseledger:136: lbc_mainnet: added BlockHeightEvent(height=668248, change=2) header blocks, final height 668248

Daemon: 2019-11-17 21:06:23,597 INFO     lbry.extras.daemon.Components:361: Started the dht

Daemon: 2019-11-17 21:06:23,597 INFO     lbry.dht.node:119: DHT node listening on UDP 0.0.0.0:4444

Daemon: 2019-11-17 21:06:23,695 INFO     lbry.wallet.ledger:107: Loaded account baZsBXCpLea1wpzn71MpMzvRmmQu7vs8k1 with 0.0 LBC, 20 receiving addresses (gap: 20), 6 change addresses (gap: 6), 0 channels, 0 certificates and 0 claims. 

Daemon: 2019-11-17 21:06:23,696 INFO     lbry.extras.daemon.Components:384: Started blob announcer
2019-11-17 21:06:23,696 INFO     lbry.extras.daemon.Components:446: start blob server

Daemon: 2019-11-17 21:06:23,696 INFO     lbry.extras.daemon.Components:421: Starting the file manager

Daemon: 2019-11-17 21:06:23,697 INFO     lbry.stream.stream_manager:148: Initializing 0 files

Daemon: 2019-11-17 21:06:23,697 INFO     lbry.stream.stream_manager:163: Started stream manager with 0 files
2019-11-17 21:06:23,697 INFO     lbry.extras.daemon.Components:427: Done setting up file manager

Daemon: 2019-11-17 21:06:23,698 INFO     lbry.blob_exchange.server:168: Blob server listening on TCP 0.0.0.0:3333

Daemon: 2019-11-17 21:06:23,773 INFO     torba.client.basenetwork:311: connected to spv7.lbry.com:50001

Daemon: 2019-11-17 21:06:23,876 INFO     torba.client.basenetwork:311: connected to spv8.lbry.com:50001

(node:3) UnhandledPromiseRejectionWarning: Error: Unknown or unsupported transport “disabled” for address “disabled:”
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3) UnhandledPromiseRejectionWarning: Error: Unknown or unsupported transport “disabled” for address “disabled:”
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:3) UnhandledPromiseRejectionWarning: Error: Unknown or unsupported transport “disabled” for address “disabled:”
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:3) UnhandledPromiseRejectionWarning: Error: Unknown or unsupported transport “disabled” for address “disabled:”
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:3) UnhandledPromiseRejectionWarning: Error: Unknown or unsupported transport “disabled” for address “disabled:”
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
Daemon: 2019-11-17 21:06:23,946 INFO     torba.client.basenetwork:311: connected to spv9.lbry.com:50001

Daemon: 2019-11-17 21:06:29,048 INFO     lbry.dht.protocol.routing_table:289: join buckets 2

Daemon: 2019-11-17 21:06:29,049 INFO     lbry.dht.protocol.routing_table:289: join buckets 1

Daemon: 2019-11-17 21:06:41,505 INFO     lbry.dht.node:159: Joined DHT, 14 peers known in 3 buckets

Daemon: 2019-11-17 21:07:02,957 INFO     torba.client.baseledger:136: lbc_mainnet: added BlockHeightEvent(height=668249, change=1) header blocks, final height 668249

Daemon: 2019-11-17 21:08:59,444 INFO     torba.client.baseledger:136: lbc_mainnet: added BlockHeightEvent(height=668250, change=1) header blocks, final height 668250

Daemon: 2019-11-17 21:10:44,553 INFO     torba.client.baseledger:136: lbc_mainnet: added BlockHeightEvent(height=668251, change=1) header blocks, final height 668251

Daemon: 2019-11-17 21:12:09,489 INFO     torba.client.baseledger:136: lbc_mainnet: added BlockHeightEvent(height=668252, change=1) header blocks, final height 668252

Daemon: 2019-11-17 21:12:49,494 INFO     torba.client.baseledger:136: lbc_mainnet: added BlockHeightEvent(height=668253, change=1) header blocks, final height 668253

**Comment by tzarebczan** [comment]
The app currently requires gnome-keyring to be installed. Please try that and let us know. 

If not, you can check out lbry.tv instead

**Comment by danrobi11** [comment]
I have gnome-keyring installed. 
Should i install also gnome-keyring-pkcs11? (GNOME keyring module for the PKCS#11 module loading library)

**Comment by tzarebczan** [comment]
If you installed it recently, it may need a reboot. 

Also, were you prompted for a keychain password on startup? If you decline that, the white screen will happen and may require a restart of the pc. You can quit the app with Ctrl-q to try that also.

**Comment by danrobi11** [comment]
Okay, you're right. I did decline once a keychain password. Thank you thomas ;)
