### ISSUE TITLE
spee.ch wallet sync / balance issues

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2627]
Spee.ch wallet goes out of sync and loses track of LBC / address subscriptions. 

Need to see why this is happening on larger wallets like spee.ch

**Comment by tzarebczan** [comment]
This might be related to utxos getting reserved, will continue to monitor. Workaround would be to add a job that runs utxorelease every x minutes, but the real solution is #2375

**Comment by lyoshenka** [comment]
we think #2744 will solve this
