### ISSUE TITLE
headers syncing megaissue

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2631]
- [x] akin getting hangups while syncing headers, see Slack. It needs to better support and handle timeouts/retries (to other servers?)

- [x] can't ctrl-C / shutdown while headers are downloading - takes 10+ seconds

- [x] make sure headers download percentage starts from 0 if new blocks are being downloaded on startup (to account for any missing blocks since last run). Currently this would show something like 97% if it was almost caught up. Starting from 0 will give a better indication of progress to the user. 

-  [ ] determine source of delay: Between finishing headers download and address subscription, there is a 4 second delay. 

```
019-11-22 10:27:27,515 INFO     torba.client.baseledger:329: Headers sync: 670774 / 670774
2019-11-22 10:27:31,499 INFO     torba.client.baseledger:297: Subscribing and updating accounts.

```

- [x] ? package headers with lbrynet executable. This would auto-extract the headers into the data directory if they don't exist. 

Bonus: 
- [ ] figure out why verification takes 30+ seconds on slower disks 
```
2019-11-25 18:48:36,546 INFO     lbry.extras.daemon.Components:180: remote height: 668566, local height: 671984
2019-11-25 18:49:32,715 INFO     lbry.extras.daemon.Components:220: Header checkpoint verified.
```

**Comment by shyba** [comment]
1, 2 and 3 on: https://github.com/lbryio/lbry-sdk/pull/2656

**Comment by lyoshenka** [comment]
moved last item into its own issue: https://github.com/lbryio/lbry-sdk/issues/2711
