### ISSUE TITLE
Blank screen again. antix 19 new issue

### ISSUE THREAD

**Issue by danrobi11** [lbryio/lbry-sdk#2691]
Hi. Since new update 0.38 this issue is fixed:https://github.com/lbryio/lbry-sdk/issues/2626 
Thanks for that. However, now it goes blank if i click on my video and same if i try to watch a video. 
Big problem. I cant edit my posted video because of this issue.
I got 2 little demo video here:
https://open.lbry.com/lbry-issue-2019-12-21_14.48.05#efa06655f83ed65f971bc6e1159152073603fe58
https://open.lbry.com/lbry-issue2-2019-12-21_14.58.14#61dae9cd16eef371efe3a2463895d209b7c11049
---------------------------------------------------------------------------------------
Also, this video does not work on lbry.tv and its the same type file MP4:
(No compatible source was found for this media.) 
https://open.lbry.com/How-To-MuWire-Chat-Functionality-Demo#1253fd30b901a1bea613ff4daf1be36f4b4e9bd1

**Comment by tzarebczan** [comment]
Sorry for the trouble. We'll need to look why that may be failing for you. Can you press ctrl-shift-I to open the console and then try entering the page. Any errors there? If not, we can do a remote session together - contact me at @jiggytom on chat.lbry.com. 

Going to close this for now since it belongs in the desktop app repo and may be something specific to your install.

**Comment by tzarebczan** [comment]
As far as the video, try one with the mp4 extension to see if that works. If not, it may be an issue with a nonstandard resolution.

**Comment by danrobi11** [comment]
Ok. I've opened the console and clicked on one of my video. Heres the result:
https://open.lbry.com/lbry-issue-testing-console-2019-12-21_15.39.20#9555dbc1283577bcb1616dd974c06ea0a8625ec8
'try one with the mp4 extension' Whats that?

**Comment by danrobi11** [comment]
Also, i cant fetch rewards

**Comment by tzarebczan** [comment]
Both issues might be related to the keychain password - did you not get prompted? It may not work well with your OS + the startup minimized setting. Try disabling that and then also quitting the app with Ctrl-Q and then restart it.

**Comment by danrobi11** [comment]
'Try disabling that' 
Disabling what? Explain a bit more. Im not an IT guy.

**Comment by tzarebczan** [comment]
The option at the bottom of settings for starting minimized.

**Comment by danrobi11** [comment]
Nah, same with the starting minimized disable. And i did not had any keyring, the app just opened normally

**Comment by tzarebczan** [comment]
Even after quitting with Ctrl-q and restarting? 

There will be a patch out later today, maybe you can try again with that one.

**Comment by danrobi11** [comment]
Ya i did ctrl + q
Ok will try. Thanks!
Note: I know its antix the problem. LBRY not the only app that im having issue with on antix. Im just letting you guys know about it. I'll change OS, antix not for a noob like me

**Comment by danrobi11** [comment]
I forgot to mention that i cant sing in. For the first time that im trying to add my email it doesnt work, thats really funny. Im clicking on continue but nothing is happening.

**Comment by tzarebczan** [comment]
All those problems are related to the same issue with your keyring.

**Comment by danrobi11** [comment]
Hi. Same with 0.38.2

**Comment by danrobi11** [comment]
Can i create a new account from lbry.tv and link it to my existent anonymous lbry desktop account, from lbry.tv? 
I would really like to be able edit my posted video lol. Can we edit our posted videos from lbry.tv?

**Comment by tzarebczan** [comment]
No, that's not possible without the email, sorry.

So have you already tried disabling the start minimized setting to see if that helps? Are you not prompted for a keyring password if you quit the app with ctrl-Q and restart? 

Maybe you can install Seahorse and then clear out the keychain. You won't loose anything locally. 

The other option is to copy your wallet file to a new PC and sign in there. See Help page to find where it's located.

**Comment by danrobi11** [comment]
Hi. Im now running MX Linux (MX-19) and LBRY finally working.
This video doesnt work with the LBRY app but it does work on lbry.tv
https://lbry.tv/@Danrobi:b/How-To-MuWire-Chat-Functionality-Demo:1

**Comment by tzarebczan** [comment]
Glad it's up and running. The m4v issue should be fixed in the next patch...which is already up on the web.

**Comment by danrobi11** [comment]
Great, thanks. Merry Christmas :)
