### ISSUE TITLE
Feature request:  dynamic trending. Spreading the feed through Support/tip capping or lottery.. 

### ISSUE THREAD

**Issue by rainbowjaw** [lbryio/lbry-sdk#2714]
lbry/wallet/server/db/trending.py

**_Purpose of a feed:_**
I'd argue that the main purpose of a feed should be to help and guide a user to find "**interesting**" and relevant content.  The idea of a trending feed is to help sort what is most interesting in the current moment. 

**_The problem:_**
The current trending algo is stale. It does not encourage **interestingness**, or even **variety**.   It keeps the highest (fresh) bidders at the top, with little opportunity to compete in rank except through matching financial bid.  This leads those who have either the greatest financial incentive or financial means to dominate the top of the trending board. 
_This is bad for publishers_  
LBC whales can easily hold their position.  Top 10 starts to get crowded really quick, and poor or new publishers have little chance at discovery.  At a certain point there becomes no reason to stake at all, as it is too expensive for the probable views. Low discovery leads to less reasons for anyone but LBC whales to publish. 
_this is bad for viewers_ 
Every time you log on, you see content only from LBC whales.  And worse, it's the same whales every time there is **no variety**.  At a certain point you have to jump straight to page 5 or scroll for 30 seconds before seeing anything new.  

**_A Solution:_**
Instead of having a king of the hill setup, consider something like tiered lottery pools.   Take the top 100 bids, and randomize their position on the feed at a refresh point. the next pool could open the pool to be wider like top 101-1000 or simply 101-200.

This creates a lower barrier of entry while encouraging more users to stake by making more opportunity for discovery as a publisher. Even if the highest individual staking amounts are lowered this way, balance can be found by spreading opportunity to more users able to afford the lottery/reach lower staking amounts.  LBRYIO can adjust these values to create the right balance of freshness and staking incentive (pool size enlarged as platform adoption occurs).   Or better yet give the user control over these variables right in the app on a slider, although i'm guessing this is opposed to the business model. 

While this solution does not tackle the **interestingness** of content the feed *directly*, it does provide **more variety**, while maintaining a system built on staking.  By providing the user more variety, it exposes the user to a larger pool of content and enables them to discover what *they* find the most interesting. 

There are possible complications to this solution when it comes to difference in activity on tags, how the lottery can scale when comparing an highly active tag with a less active tag.

**Comment by tzarebczan** [comment]
Thank you for the writeup and concerns! Per our discussion on DIscord, this would still be susceptible to similar dynamics since we can't tell who is who on the blockchain. In the long term, we think this can be solved with a web of trust.  In the short term, we will consider using an alternate trending algorithm which is at least more dynamic.
