### ISSUE TITLE
Support xenial

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2741]
With the latest release, users will see: 
```-Daemon: [5973] Error loading Python lib '/tmp/_MEIoQcg4u/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIoQcg4u/libpython3.7m.so.1.0)
```

The flatpak does work for these users, it must be encapsulating the environment .

**Comment by eukreign** [comment]
fixed in #2796
