### ISSUE TITLE
Add analytics event to publish success/failure in clients

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#2745]
The analytics events are here https://github.com/lbryio/lbry-sdk/blob/master/lbry/extras/daemon/analytics.py

We need a new event that tracks calls to the `publish` API endpoint and whether each publish succeeds or fails.

**Comment by 7astro7** [comment]
I would like to help out with this but am pretty new to open source. I have a couple questions and if it's alright to work from your feedback to solve this please let me know. My questions are 
1. Would a new event that tracks calls to the ```publish``` API endpoint include something like ```PUBLISHED = 'Publish Success'``` under ```# Things We Track```?
2.  Would the new event also include something like 
```python
async def send_publish_success(self):
    await self.track(self._event(PUBLISHED))
```
? 
Thank you!

**Comment by lyoshenka** [comment]
Great to hear that you want to tackle this.

1. Yes. I'd call the event `Publishes`, and then pass the outcome (success or failure) as a property to the event.
2. yes. you can copy `send_server_startup_error`, which includes the `message` property but you can that an `outcome` property with "success" or "failure" as the options

**Comment by svshivapuja** [comment]
Is this issue still open @lyoshenka ?

**Comment by lyoshenka** [comment]
yep

**Comment by FemtosecondLaser** [comment]
I created the pull request #3452 (which aims to resolve the issue), but I, allegedly, do not have permissions to link the pull request to the issue. Based on the information I found on the web - there is supposed to be a cog-like button on the sidebar of this page, but I do not see one.

**Comment by lyoshenka** [comment]
@jackrobison is right that we're moving away from tracking events like this in our analytics. thanks for your PR @FemtosecondLaser and sorry that we didn't close this issue earlier
