### ISSUE TITLE
BitTorrent support v1

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#2767]
This issue can be closed when:
- you can call `get` on a LBRY URI that points at a claim with a bittorrent infohash in the metadata
- when you call `get` on such a claim, the SDK downloads the content from bittorrent
- `file_list` returns the appropriate data for that content 
- `claim_search` does not return bittorrent results unless `--include-bittorrent-sources` flag is passed (if this is hard to do, discuss with grin for a better way to solve https://github.com/lbryio/lbry-sdk/issues/2767#issuecomment-582651158)

Outstanding questions:
- what is "appropriate data" for `file_list`

**Comment by kauffj** [comment]
In terms of a releasable SDK, we need to also ensure BitTorrent client is only returned to clients that support it. The primary issue here is having BitTorrent results showing up prior to lbry.tv support.

If `claim_search` omits BitTorrent results unless specifically requested while BitTorrent is in "beta", that would probably get us there.
