### ISSUE TITLE
"Extraneous parameters for stream_list command: resolve"

### ISSUE THREAD

**Issue by Lukewh** [lbryio/lbry-sdk#2781]
Calling with:
`./lbrynet stream list` and `./lbrynet stream list --resolve` both trigger this error.

Version 0.58.2

**Comment by tzarebczan** [comment]
Hey, thanks for reaching out! The resolve param was adding only recently and there will be a release with it out later today. It should work fine without it on 58.2, just tried that.

**Comment by Lukewh** [comment]
Just updated to latest version:
```
$ ./lbrynet --version
lbrynet 0.59.0
$ ./lbrynet stream list
{
  "code": -32602,
  "data": {},
  "message": "Extraneous parameters for stream_list command: resolve"
}
```

**Comment by tzarebczan** [comment]
I think you are running the CLI from one binary (old) but lbrynet is
running from the latest.
