### ISSUE TITLE
stream type times out via json rpc

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2786]
```{"jsonrpc":"2.0","method": "claim_search", "params": {"stream_types": ["video"]}}``` fails

```lbrynet claim search --stream_types=video``` works

**Comment by tzarebczan** [comment]
forced query time out on both, from CLI you see:
```SELECT count(*) as row_count FROM claim WHERE claim.stream_type IN (1, 1)```

From JSON: 
```SELECT count(*) as row_count FROM claim WHERE claim.stream_type IN (1)```

**Comment by tzarebczan** [comment]
Happens on claim type now also...

**Comment by lyoshenka** [comment]
Weird that the first query has a duplicate param: `claim.stream_type IN (1, 1)`. Prolly not related to the slowness, but still.

**Comment by tzarebczan** [comment]
And that's the one that works!

**Comment by tzarebczan** [comment]
Still seems to be an issue: 
timeout:
```{"jsonrpc":"2.0","method": "claim_search", "params": {"stream_types":  ["video"]}}```

works: ```lbrynet claim search --stream_types=video```

**Comment by tzarebczan** [comment]
We found out this is due to some defaults being passed from CLI, which was helping filter down some records and make it performant.

**Comment by tzarebczan** [comment]
This is fixed with new indexes
