### ISSUE TITLE
Missing indexes 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2801]
The app is planning to add more filtering to claim search, but there's some missing indexes between these parameters and various sorting methods. 

One example is that ```lbrynet claim search --stream_types=video --order_by=release_time``` fails, but if you remove the release time sort, it works. There are probably others in the same boat. 

Pretty much every combination of claim search params should work with every combination of filtering /sorting.

**Comment by jessopb** [comment]
From discussion with Jack, the order_by is what pushes the time over the limit.

To clarify, we want to be able to successfully filter claim search on any combination of the following fields:
claim_type
stream_type
release_time (comparison)
duration (comparison)
channel_id
any_tags
not_tags
any_languages

And then order by any other reasonable column without it timing out.

**Comment by tzarebczan** [comment]
This is one we need sooner than later: ```{"jsonrpc":"2.0","method":"claim_search","params": {"claim_type": "channel", "not_tags": ["porn", "nsfw", "mature", "xxx"], "order_by": ["trending_group", "trending_mixed"]},"id":1573753506065}```

Release time and effective amount order bys work.

@seanyesmunt is working on a new following feature and we need to display trending channels.  Can we confirm it's missing and it be added to the latest SDKs manually (+ PR'd).

**Comment by tzarebczan** [comment]
This should be fixed now, thanks @eukreign !
