### ISSUE TITLE
Make ffmpeg work again

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2850]
To revert https://github.com/lbryio/lbry-sdk/pull/2845 and support dht + windows + ffmpeg

**Comment by jessopb** [comment]
Also optimize flag throws error on stream update.

**Comment by jessopb** [comment]
if I delete ffprobe and/or ffmpeg from the which path, ffmpeg_find still reports available.

**Comment by tzarebczan** [comment]
Are you using ffmpeg_folder config? If not, maybe it's finding it from your system path.

**Comment by jessopb** [comment]
typing which ffmpeg yields nothing. it's not where it's saying it is.
