### ISSUE TITLE
force mp4/use ffmpeg metadata if file does not require transcoding, but missing metadata

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2868]
For MKV files (and possibly others), you get the below. Which means we don't populate metadata for it, i.e. height and width. If we forced mp4, it should, or if we read the data from ffmpeg instead. 

```
2020-03-19 17:45:51,686 ERROR    lbry.schema.attrs:67: Could not extract height from file metadata.
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry-sdk\lbry\schema\attrs.py", line 65, in _extract
    setattr(self, field, file_metadata.getValues(field)[0])
IndexError: list index out of range
2020-03-19 17:45:51,694 ERROR    lbry.schema.attrs:67: Could not extract width from file metadata.
Traceback (most recent call last):
  File "c:\users\thoma\documents\lbry-sdk\lbry\schema\attrs.py", line 65, in _extract
    setattr(self, field, file_metadata.getValues(field)[0])
IndexError: list index out of range```

**Comment by BrannonKing** [comment]
This was an MKV file that contained H264/AAC encodings. I think that combo was the problem. H264/AAC are typically put in MP4 containers. MKV can contain most anything. WEBM is a restricted set of MKV where the video is VP8/VP9/AV1 and the audio is Vorbis/Opus. Web browsers typically handle the webm subset without issue.

Whenever the SDK transcoder runs, it chooses the correct container format to match its encoders. However, it does not presently detect a fault when the contained encodings are approved and the container is approved -- it doesn't try to verify that the encodings match the container in that situation. Maybe it should.

The error posted above is a hachoir failure, not an ffmpeg failure. In addition, no web browsers attempt to play MKV files directly. If you rename it to have a webm extension, then Chrome will play the file and Firefox won't.

Possible fixes:
1. Add an additional transcoding check to ensure that H264 data is in an MP4 container, and that any mkv files receive a webm extension (assuming they have proper contents).
2. In the `Stream.update` function, where we query the file metadata via hachoir, we could chose to query it via FFprobe instead (and fall back to hachoir if that failed, or ditch hachoir all together). FFprobe does not fail on unusual MKV files. I can't see it failing on any image/video/audio file that we would care to support.
