### ISSUE TITLE
Return pending transactions with transaction_list (bad date bug)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#2903]
If I send a tip:

- It shows successful
- My balance changes
- App directs me to my history

But the transaction isn't there!

**Comment by tzarebczan** [comment]
Probably https://github.com/lbryio/lbry-sdk/issues/2639 . Did you confirm via a transaction list call vs maybe some UI bug?

**Comment by tzarebczan** [comment]
Turns out the issue is that the date on pending transactions/claims/etc get set to June 22, 2016 (blockchain start time) so the items are sorted at the bottom of the list. I made @shyba aware of this, we should get a patch out with a fix.

**Comment by tzarebczan** [comment]
This is fixed in 0.68
