### ISSUE TITLE
Check audio and downsample with ffmpeg

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2906]
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1422684, anything over 48kHZ won't play on Windows + FF. We should make this part of the checks and resample (-ar param)

**Comment by Death916** [comment]
https://github.com/lbryio/lbry-sdk/pull/2933

**Comment by tzarebczan** [comment]
This was completed.
