### ISSUE TITLE
Blob unavailability from a single peer causes download to fail

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-sdk#2938]
I am trying to download lbry://Discussing-Blockchain-And-Crypto-With-Rice-Crypto-1#2adece5e9ee14ea239062026104e11adc6134c5e

It gets about halfway then a blob unavailability message appears from a non-reflector peer. However, the download totally stops after that.

It should switch to another peer.

**Comment by tzarebczan** [comment]
Can you share the log file? It should not stop if it can still hit reflector and should continue to find other peers (but since this file was new, there were probably none).

**Comment by eggplantbren** [comment]
Here you go. There's a lot else going on but you can search for blob not in availability, and you can see me trying to restart it several times. Your explanation makes sense but I still think it could recover a lot more gracefully like BitTorrent would (wouldn't it just start downloading again as soon as a peer appeared?). Sorry if this is a feature request and not a bug report.

file:///home/brewer/Desktop/lbrynet.log

**Comment by eggplantbren** [comment]
Also, when I try to use `lbrynet get` to complete the download, it sometimes says I already have the stream, which I don't. Does that refer to the full file or the blobs? Sometimes deleting the file gets rid of that message, but other times it doesn't.

**Comment by tzarebczan** [comment]
We try to download for a couple minutes and then give up. It would retry on restart or if you call get again.

That means you have a file list record for it and it should try to redownload it. 

Closing this for now.
