### ISSUE TITLE
Balance is suddenly 0.0 LBC

### ISSUE THREAD

**Issue by eric-saintetienne** [lbryio/lbry-sdk#2949]
Hi,

Consider this address which holds about 117 LBC: https://explorer.lbry.com/address/bDmm5b8HXgkMD3Cz273bpmbj52r3SMmpra

It address belongs to one of my accounts (I've redacted the account id):
```
$ ./lbrynet address is_mine --account_id=ACCOUNT_ID_REDACTED bDmm5b8HXgkMD3Cz273bpmbj52r3SMmpra
true
```

How's the following possible?
```
$ ./lbrynet account balance ACCOUNT_ID_REDACTED
{
  "available": "0.0",
  "reserved": "0.10000163",
  "reserved_subtotals": {
    "claims": "0.10000163",
    "supports": "0.0",
    "tips": "0.0"
  },
  "total": "0.10000163"
}
```

And more importantly how can I recover those orphaned LBC?

It's not the 1st time it happens, I've already lost 191 LBC suddenly that I'd like to recover.

Thank you.

**Comment by eukreign** [comment]
Hard to tell what happened with just the information you've provided but you can try deleting the `bockchain.db` file in `[your wallet directory]/lbc_mainnet/blockchain.db` and then when you restart your `lbrynet` daemon it will re-sync and hopefully the problem will be corrected.

`blockchain.db` is a cache file so it is always safe to delete it (unlike your wallet file, which you should never delete) and it will just download all of your transactions again.

**Comment by eric-saintetienne** [comment]
Found it, for whomever have this issue in the future:

```
./lbrynet utxo release
null
```

Thanks!

**Comment by eukreign** [comment]
Deleting the `blockchain.db` should have worked, it's a hard version of `utxo release`. If `utxo release` worked then deleting `blockchain.db` should have definitely worked (but `utxo release` will be a lot faster than sync'ing from scratch).
