### ISSUE TITLE
The pre-built binary "lbrynet" file doesn't launch on linux 32bits system

### ISSUE THREAD

**Issue by Faign** [lbryio/lbry-sdk#2998]
The command `./lbrynet start` returns `-sh: ./lbrynet:cannot execute binary file` even after a `chmod +x lbrynet`

**Comment by tzarebczan** [comment]
Thanks for reaching out! Unfortunately we only support 64 bit versions on Linux for our binaries. Building a 32 bit binary would require a bit more work and is not a common request. 

Your best bet would be to compile your own following: https://github.com/lbryio/lbry-sdk/blob/1e478e354599eb71664b8cb912b54a9af8f31db3/.github/workflows/main.yml#L68
