### ISSUE TITLE
sync_hash fails if encrypted on disk = true, but wallet not encrypted (is_encrypted shows true in wallet status also)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#3026]
There are some scenarios where the encrypted on disk value is incorrect(one is: if sync apply with a blank password was used on an encrypted wallet) and in this case, sync hash fails when run. But after the app runs sync apply to get a new hash, then sync hash works again. 

Error: 'NoneType' object has no attribute 'encode'

It should not fail and should try to run the hash knowing that the wallet is not encrypted and the encrypted on disk value is 
incorrect. 

This prevents startup on Android and causes issues on desktop/lbry.tv as well.

is_encrypted in wallet status should also be false.  encrypted on disk setting should be reset in wallet.

**Comment by jessopb** [comment]
bump
