### ISSUE TITLE
Add integration for new comment server methods

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-sdk#3035]
## Comment Server was upgraded to the official JSON RPC 2.0 Spec

- [ ] everything now user `/api/v2` 
- [ ] non-zero `id` must be sent, or it is considered a notification which gets no response.
- [ ] methods are now referenced with a service so `<service>.<method>` ie `comment.List`. See list below

#### Transitioned APIs
- `get_claim_comments` =>    `comment.List`
- `get_claim_hidden_comments` =>   `comment.List`, paramter added to main list api
- `get_channel_from_comment_id` => `comment.GetChannelFromCommentID`
- `create_comment` => `comment.Create`
- `abandon_comment` =>  `comment.Abandon`
- `edit_comment` => `comment.Edit`

### New APIs

- `react.List` 
#### Request
```golang
type ListArgs struct {
	CommentIDs  string  `json:"comment_ids"`
	Signature   string  `json:"signature"`
	SigningTS   string  `json:"signing_ts"`
	Types       *string `json:"types"`
	ChannelID   *string `json:"channel_id"`
	ChannelName *string `json:"channel_name"`
}
```
Channel name plus timestamp should be signed, in order to get a list of both yours and others reactions

- `react.React`
#### Request
```golang
type ReactArgs struct {
	CommentIDs  string  `json:"comment_ids"`
	Signature   string  `json:"signature"`
	SigningTS   string  `json:"signing_ts"`
	Remove      bool    `json:"remove"`
	ClearTypes  string  `json:"clear_types"`
	Type        string  `json:"type"`
	ChannelID   *string `json:"channel_id"`
	ChannelName *string `json:"channel_name"`
}
```
Channel name plus timestamp must be signed

**Comment by tzarebczan** [comment]
This was done.
