### ISSUE TITLE
API SDK retrieve the list of all supports and tips to a video 

### ISSUE THREAD

**Issue by codepujan** [lbryio/lbry-sdk#3038]
Is there a way to retrieve the list of users, and the amount of support to a particular video? 
For instance , this video : 
https://lbry.tv/@Learn-LBRY:6/how-to-fix-vcruntime140.dll-missing-error-in-valorant:f has 18 LBC of supports and tips . Is there a way to get the list of channels and the tip amount? 
 I tried using the  support list endpoint . 
The video has claim_id as fe442d3fc15c1281fb4f968edf3bc51b22917c76 (retrieved from the video information) .
I executed : 

`lbrynet support list --claim_id=fe442d3fc15c1281fb4f968edf3bc51b22917c76`

and it returns me : 

`{
  "items": [],
  "page": 1,
  "page_size": 20,
  "total_items": 0,
  "total_pages": 0
}`
 I am not the creator of the video or neither have I supported / tipped the video . 

I have tried this with multiple videos and claim ids , and this doesnt seem to work .  Any help would be appreciated , 

Regards !

**Comment by tzarebczan** [comment]
This is not possible yet, but we do plan to implement it. Working through a big refactor and a few other issues at the moment. 

Support list will only show local wallet data, but the plan is to have a new api with all.

Will be covered under https://github.com/lbryio/lbry-sdk/issues/2041

**Comment by codepujan** [comment]
Hey @tzarebczan . Thank you for your follow up. Instead , Can I just get a full list of all supports/tips , not searchingby claim id . Analogous to the command  
`lbrynet claim search
`which seems to list all the claims . 
I am trying to  get a hand on the list of supports by any way possible. Please help!
