### ISSUE TITLE
Include URL of signing channel in txo_xyz responses

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#3067]

**Comment by tzarebczan** [comment]
Also allow filtering by this (include/exclude)

**Comment by tzarebczan** [comment]
@lyoshenka since we have the LBRY ones signed ones now, it would be nice to support signing channel param on txo *

**Comment by lyoshenka** [comment]
to get the URL, pass `--resolve`. the two issues from the comments are split out into #3155 and #3156
