### ISSUE TITLE
RSS/XML :  To determine a section or category

### ISSUE THREAD

**Issue by inDreamXtrem** [lbryio/lbry-sdk#3079]
Hi,
is it possible to have a field in the RSS file to determine a section or category?
Or be able to create playlists available in RSS format.

Thanks for your great job,
have a good day!

**Comment by tzarebczan** [comment]
Thanks for the isssue! We have this covered on the app side and it could be done with tags and/or playlists when we implement RSS: https://github.com/lbryio/lbry-desktop/issues/3779

**Comment by inDreamXtrem** [comment]
Ok, Thanks!! 👊
