### ISSUE TITLE
Claim search claims_per_channel improvement (or new param?)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#3080]
Right now the claims per channel filtering is applied across all claims and pages that meet the result criteria, which causes only a small subset of results when used alongside a list of channels claim ids. 

The original goal was to limit duplicate claims from the same channel, which it does, but also too aggressively. It should only consider them duplicates if they are within the some release time (or created at if release is null) period (i.e. 1 day). Would it make sense to make this comparison period an additional parameter instead of hard coding?

**Comment by kauffj** [comment]
This requires some more discussion and consideration about what is the best approach. App-side roll up, as well as a parameter that acts as a minimum gap before repeating a channel, or something not yet thought of could all be a better solution.

**Comment by kauffj** [comment]
@shyba has flexibility in how this is done. The core requirement is to deliver results with a flexible parameter for the total limit from a creator or how many items before a creator is repeated.
