### ISSUE TITLE
There is a bug somewhere

### ISSUE THREAD

**Issue by nathgit** [lbryio/lbry-sdk#3091]
When trying to login to lbry on an android phone, I get an error message that says:
" `There is a bug somewhere
Try refreshing to fix the issue, If that doesn't work email help@lbry.com for support.
` "
I have tried to login in 3 different browsers. When I login it briefly goes to the homepage, then redirects to the error message.
android version:6.0,1
chrome version:55.0.2883.91
hermit version:15.5.2
link bubble version:1.9.58

hermit is "lhermit lite apps browser". It's on the play store.
link bubble is also on the play store.

**Comment by nathgit** [comment]
I can login on desktop (chromebook) just fine.

**Comment by tzarebczan** [comment]
Please email us as requested and we'll take a look at the account.
