### ISSUE TITLE
sqlite too many variables error on windows in new SDK

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry-sdk#3096]
when running the wallet unit tests in new SDK on windows on GitHub CI it throws the sqlite too many variables error (works fine on linux and mac CI)

probably fix needed here (add code here to check if we're on sqlite and then split up the list into smaller batches): https://github.com/lbryio/lbry-sdk/blob/ec89baa831692975a959fb86beed7672757bae11/lbry/db/queries/address.py#L61

**Comment by shyba** [comment]
merged where it was being raised. Nothing else to do unless we compile sqlite ourselves on windows build

sqlite 3.32 also solves it by default if there is a way to upgrade
