### ISSUE TITLE
LBRYnet headers contains "'Server': 'Python/3.7 aiohttp/3.5.4'"

### ISSUE THREAD

**Issue by jamiejackherer** [lbryio/lbry-sdk#3108]
I am attempting to create an async python API client for lbrynet based on pybry. I am using the pybry source to rebuild from.

When making requests to the lbrynet server, it returns headers:

`<CIMultiDictProxy('Content-Type': 'application/json; charset=utf-8', 'Content-Length': '130', 'Date': 'Wed, 09 Dec 2020 19:28:00 GMT', 'Server': 'Python/3.7 aiohttp/3.5.4')>`

I am curious where these values are coded in, I have searched the lbry-sdk repo but cannon find the values. 

I am wondering if these are hardcoded in or how they come about.

**Comment by eukreign** [comment]
It is added by `aiohttp` library which is what we use for our HTTP stack.

**Comment by jamiejackherer** [comment]
OK I understand now. The pre-built binary is built with aiohttp==3.5.4 and Python3.7. Thanks, I will build from source. i am still trying to figure it all out.

**Comment by eukreign** [comment]
Also, keep in mind that the `lbrynet` command is already an *async python API client for lbrynet*. Since when you run `lbrynet` it connects to its own running instance using JSON RPC.
