### ISSUE TITLE
Signing API

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-sdk#3109]
Hi Team, 

We would like be able to move faster and use external services. We need an API that takes arbitrary data and signs its. Right now the only way is to create new APIs in multiple places which slows velocity and is more work.

**Comment by tiger5226** [comment]
@kauffj @tzarebczan @eukreign

**Comment by eukreign** [comment]
I support this.

**Comment by tiger5226** [comment]
I think sdk needs to know which channel to sign as too because a user could be associated with more than one identity.

**Comment by tiger5226** [comment]
@seanyesmunt We discussed this, FYI

**Comment by lbry-boost** [comment]
Would love to see extension of this API in a form of "login through LBRY" capability. The only reason why I don't do account system on my website is that I don't want to do yet another users & passwords system. I would rather prefer to let people login through LBRY API with message signing. In my mind it looks as following:
1. User is logged in on Odysee and wants to login on 3rd party website
2. 3rd party website sends a sign request to Odysee where user confirms signing
3. 3rd party website verifies the sign and authenticates the user (as a channel)

If you ever decide to do that, let me know and I will be glad to develop backend on my side and pilot this functionality with you.
