### ISSUE TITLE
Canonical URL of a stream resolves to a repost, possibly to do with matching first character of claim_id

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-sdk#3112]
There is a claim `lbry://gone-with-the-wind:8b1a77c93ecb7150313630e1548be99ad6b4ddd2` which is a stream. It is currently controlling the name, and `lbrynet resolve gone-with-the-wind` returns this claim, also showing its canonical_url to be `lbry://gone-with-the-wind:8`.

However, if you resolve the canonical URL, you don't get the stream back. Instead you get the claim `8067137a29ce462fdc2f82c880c727d5383d76a4` which is a repost of it. I think this happened because the first character of the claim_id is an 8.

This makes the app enter an infinite loop of resolves if you try to go to the stream.

**Comment by tzarebczan** [comment]
Thanks for filing. Same as https://github.com/lbryio/lbry-sdk/issues/2982 and I think it's fixed in the sdk rewrite.
