### ISSUE TITLE
Use new sdk postgres from spv server

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry-sdk#3116]
The existing spv server can perform better by passing claim search and resolve off to a remote postgres full-sdk-node server. This would allow the spv server to not use slow sqlite/multiprocessing and give feedback on the performance of searches/resolves using postgres.

- [ ] add new sdk group to lbrytv and an additional spv server for them, use this group to test the changes
- [ ] run postgres server and full sdk node on sdk.lbry.tech (or an equivalent new server) 
    - [ ] monitoring for if it crashes and the performance of keeping up with block sync
- [ ] copy/paste claim search query generation from `fast_wallet_server_sync`
- [ ] add sqlalchemy requirement for spv server and update docker build
- [ ] add postgres connection info to spv server settings
- [ ] add optional arg for claim search and resolve in the spv client/server to enable passing the search/resolve to postgres instead of doing it in sqlite on the spv server.
    - [ ] add sqlite vs postgres field to prometheus
- [ ] add whether or not postgres is supported to `server.features`

**Comment by lyoshenka** [comment]
i think this also needs code in lbrytv to only send specific users to this sdk group

**Comment by shyba** [comment]
this doesn't make sense anymore, unless we update the text. I think @jackrobison is using a new setup where ES gets a whole new dedicated server, but even that is far from what is described here
