### ISSUE TITLE
Fix reorgs

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#3117]
## goal

- fix the reorg algo so it no longer breaks
- would be nice to have reproducible tests for this so we can use them against the new sdk

## plan

- force a reorg on wallet server
	- use electrumx rpc to go back 100 blocks, then let it sync forward
- check that the db is in the same state as it was before forced reorg
	- copy db before reorg
	- apply reorg
	- let it sync forward
	- open both DBs and iterate through them, checking every key and value to make sure it matches 
- look at current electrumx code to see what they've updated. get their code into our code
(needs a script to check)
- only really need to go back 1000 blocks max. reorgs don't go deeper than that

**AFTER GETTING FIX INTO PRODUCTION**, the ultimate test is to roll a chain back to 0 then forward to the tip, and it should be in exactly the same state as it is before rollback

**Comment by jackrobison** [comment]
fixed in https://github.com/lbryio/lbry-sdk/pull/3120
