### ISSUE TITLE
Blob exchange protocol

### ISSUE THREAD

**Issue by oscar60310** [lbryio/lbry-sdk#3122]
Hi,
I have studied the LBRY spec and interested in the [Blob Exchange Protocol](https://lbry.tech/spec#blob-exchange-protocol), it seems to be a five types of RPC protocol. But I don't find any implement in [blob_exchange](https://github.com/lbryio/lbry-sdk/tree/master/lbry/blob_exchange) folder, it seems to be replaced with a payment negotiation, client side sends price_request and server responses `RATE_ACCEPTED`.

May I ask why we need a new protocol to exchange blob instead of following the spec? Or I misunderstand the use of BlobServer here.

Sorry for bothering and thanks for help.

**Comment by lyoshenka** [comment]
hey, thanks for posting. here's a bit of history:

We started developing the protocol several years ago. The spec was written about a year ago to document the state of the protocol. As part of writing it, I tried to also design v2 of the protocol at the same time and write the spec as if I'm writing it for v2. So parts of the spec (like blob exchange) is aspirational - they describe how it should be done but not how it's done today.

After discussing with the team yesterday, I see how this is confusing and a mistake on my part. We need a clear distinction between how things are now and how we want them to be.

I'm going to update the spec to have a v1 and a v2. v1 will be an accurate description of the code today. v2 will be where we want to go.

If you're trying to understand how the blob exchange protocol works, the code in blob_exchange is the right place to look.

**Comment by oscar60310** [comment]
The spec is very detailed and easy to understand so I start from there, it will be great if we can figure out the difference of this SDK and the specification.

Thanks for sharing, I really like your ideas and hope it grow up in the future. 🚀
