### ISSUE TITLE
Are we able to "stream" video files in python applications?

### ISSUE THREAD

**Issue by jamiejackherer** [lbryio/lbry-sdk#3123]
How can we actually stream videos? 

For example, if I were to build a Quart (Flask) app, can I stream lbry:// URLs without actually downloading a file?

The docs for the lbry sdk are not very explanative and I am struggling to understand much of them.

**Comment by tzarebczan** [comment]
Hey there, thanks for reaching out! Yes, you can make range requests to the streaming url. You can check out how the lbry-desktop app does this. You'd need to turn off saving files and saving blobs (see https://lbry.tech/resources/daemon-settings) and then call get with the LBRY url. This will return a streaming url which you can open in your browser or VLC.
