### ISSUE TITLE
Is possible to use confirmed time as mtime when user download a file from the network?

### ISSUE THREAD

**Issue by LEETUMBRA** [lbryio/lbry-sdk#3124]
It might sounds ridiculous. It might be better if can be applied the accepted time ( That mtime ) when a file is successfully downloaded. Of course, It is said the mtime can be manipulated, at least the sdk shall apply that automatically. 

There is a background story about download problem, I personally can't find that thing at ftp, It is believed LBRY-SDK should apply the accepted date (mtime) on intended downloaded file. For example, when a grandson ask a being in 2016 via LBRY, It is suppposed the mtime of downloaded being should show 2016 instead of current.

**Comment by tzarebczan** [comment]
Thanks for opening the issue but I don't think we'll be tracking this or reporting in this way.
