### ISSUE TITLE
delete own comment and reclaim credit

### ISSUE THREAD

**Issue by cauerego** [lbryio/lbry-sdk#3133]
mistakes happen. we should be able to undo in this case!

ps: in my specific case today, though, it was even related to 2 other lbry bugs (got many accounts, selected the right one in android, moved back and forth, it went back to default. also can't choose the default.)

**Comment by tzarebczan** [comment]
You can delete comments on lbry.tv or odysee.com, but the credits you send on android are to the person you commented on as a tip.

**Comment by cauerego** [comment]
looks like commenting on android is not even bound to giving credits anymore.
