### ISSUE TITLE
Better support for finding channels

### ISSUE THREAD

**Issue by TheShanMan** [lbryio/lbry-sdk#3137]
The "Discover" feature is nice, but as the number of channels grows, it becomes less useful. I don't know how the list is ordered, but obviously you can't exhaustively scroll through it to find a content creator you're interested in.

Currently, the search feature doesn't have good capability of searching just for channels, and as I've heard, it only works if you get the channel name exactly correct. Again, not very helpful if you're trying to find out if a content creator you like is on lbry.

I'm not sure which is more feasible of 2 suggestions I have so I'll list them both and I hope this can be used to drive implementation of at least one of them.

1. Enhance the search feature to be able to restrict results to channels and do partial/fuzzy matching.
2. Add a "many followers of the xxx channel also follow this channel" where "xxx" is one of the channels you follow. In other words, when I look at the "xxx" channel or a video for it, lbry could show a message suggesting another channel I don't already follow which has a significant intersection of followers.

The goal with new users is obviously to get them to find lots of value in lbry as quickly as possible. One or both of these would make it _so_ much easier to attract and retain them in my opinion as a new user myself.

**Comment by tzarebczan** [comment]
Thanks for the feedback! 

The search features you are referring to are part of github.com/lbryio/lighthouse which has data about subscribers and view counts, this low level SDK does not. There are known issues around some fuzzy matching. Other features will be considered in the future.
