### ISSUE TITLE
How to manage the cache data

### ISSUE THREAD

**Issue by gsioteam** [lbryio/lbry-sdk#3149]
I found many large files in `.local/share/lbry/lbrynet/blobfiles/`. It almost stuff full my hard drive. Is it safe to delete those files? or any way to manage the cache size?

**Comment by tzarebczan** [comment]
This is based on a setting in advanced app options. See lbry.com/faq/host-content and https://lbry.com/faq/how-to-change-lbry-blob-files

**Comment by klesun** [comment]
Guess the rule of the thumb is to sort the files by creation date and delete from either end to keep the optimal number of seeded videos intact.
