### ISSUE TITLE
Investigate claim_search alternatives (elastic?)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#3151]

**Comment by shyba** [comment]
Elasticsearch investigated at: https://github.com/lbryio/lbry-sdk/pull/3153
I ported until all claim search tests pass and most of resolve. The app opens and you can navigate around.

Porting was easy. No schema needed, no index created and performance was enough without trying to optimize.
I did a small stress test with 1024 clients doing 10 random queries each.
The test machine is a 2 x E5-2660. 32 threads, 256gb RAM and 2 x MZ7LM240HCGR SATA SSD in RAID 0

10240 requests in 91.83033379493281, 111.50999432134311 req/s
10240 failures
latest release using sqlite, 32 cores 100%
vs
elastic search 32 cores 50%
10240 requests in 94.92767380108126, 107.87159939742844 req/s
0 failures

I will publish the test script soon, but this test only proves resilience so far as sqlite cant handle randomized queries (its hitting things that lacks an index).
Elasticsearch doesnt require creating any index so it was able to finish, even though the queries were complex enough to keep all 32 cores busy.

**Comment by lyoshenka** [comment]
elastic works and is way more performant
