### ISSUE TITLE
Error unlocking tip 

### ISSUE THREAD

**Issue by teststuff777** [lbryio/lbry-sdk#3163]
I have seen this bug from 2020. The bug is back (odysee)

**On wallet** "error unlocking tip"

**Under video :** 

(1, 'the transaction was rejected by network rules.\n\nMissing inputs\n[0100000005999835966b701a40a2b7d29be129629a74d91fa9b7eccb89f68717a25749adf3550000006a47304402201ced66025ca714ca38fb6b23068a78815f1b4d08783976b5f449b599a1f4e3f402207acdd7eeb5a5affb309dd1f7bfa88d02ee51b298688d8a9fa05b563ca9befd9d01210231efb23b92cd4067f7122da3e4c59afc991f5529fd9b8e7a12c27fb489784d29ffffffff5af89c553b390f7ca85f88b67b2d0294ebf61362c3e06d78d00ae0c183e20aca530000006a4730440220622ac217d9a95b332baefb4c1eef023fcde1c190c202d82da6004725aaaf5f19022012251d3b3979fafaf22595ecab05a02e604393643a41bd4a3b652a51e48b5f1f01210231efb23b92cd4067f7122da3e4c59afc991f5529fd9b8e7a12c27fb489784d29ffffffffb6409880b55c4a94e74db59576c709d573dba474c5fe67572a5af14d45da0875530000006b483045022100d3d7303e6281d0598d1f60cd9cdc2e3e1729b0ec35bb73985dd09c646c173ec50220455678e14e3e4a4c2a3459a39ae6a88433eb4507865e80dbc794f21ffd1bbfd901210231efb23b92cd4067f7122da3e4c59afc991f5529fd9b8e7a12c27fb489784d29ffffffff4793e6e7d0d791a1384c6a2f7cca413607867e9b6121f2f6ce45c3ca2cdb339b690000006b483045022100c462bf84ebb0ebc46a65ec2ec5f3764ccc3a803b289ad78fd3d09169c20d6f540220304c7072ac9ceaa2be69881b2a8cc76584f8056df1ea64eee406ca809c5d32c701210231efb23b92cd4067f7122da3e4c59afc991f5529fd9b8e7a12c27fb489784d29ffffffff6ee34dc5f9b2cca3282e0aef8a128fb77e0d5bc1fb560ecaac03096e40801d73000000006a47304402201fd45fe217897c5de2a56d07dbfa691b5724c9db8e7bae34a18551895c73e4b0022057c3199bea98a97c0b1abfb04a56ce60e2f3da1361b51d43f911c08359e65fbe01210231efb23b92cd4067f7122da3e4c59afc991f5529fd9b8e7a12c27fb489784d29ffffffff02521a02000000000062b63046534f43494554592d2d2d56657273696f6e2d636f757274652d64752d646f63756d656e74616972652d2d56455146531433fa1830bb6358fe35114962485e69c8dbbb027f6d7576a9144aae2d7d5efc2ca2550d2c996d140da7033c3f5e88ac2e447b17000000001976a9144aae2d7d5efc2ca2550d2c996d140da7033c3f5e88ac00000000]').

Done

**Comment by tzarebczan** [comment]
Sorry about that. Please try again, there were some issues earlier. They did actually unlock. If you continue to have issues, email us at hello@lbry.com
