### ISSUE TITLE
DHT memory leak

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#3182]
DHT peer manager class tracks last_sent and last_requested and last_replied for every (ip, port) tuple. These dicts keep growing and growing as the node runs.

Solution: use a fixed-size data structure, like an LRU cache or ring buffer.

To reproduce: add a million random peers to the peer manager, call [this function](https://github.com/lbryio/lbry-sdk/blob/master/lbry/dht/peer.py#L58) on each, then drop them all. `last_seen` and `last_requested` will grow without bound. We need to cap how big they can get.

Also look at `prune()` in peer_manager, and at test_peer.py in dht unit tests.

Est: 1 day of work

**Comment by nishp77** [comment]
@lyoshenka hi i'm new to the project, however is there any documentation? couldn't find one. Does peer manager act more like a tracker of activity for all peers? If we use LRU cache, we need some capacity, what would it be?

**Comment by lyoshenka** [comment]
@nishp77 thanks for your interest here. there's not much documentation. we're working on improving that. 

the peer manager makes sure that there's only one instance of each peer so you're not creating duplicate objects. it does also track activity for all the peers.

@jackrobison do you have any recommendations on what size LRU cache is good here. i would guess 10000 is fine
