### ISSUE TITLE
Fix client reconnection issue

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#3194]
The last update has introduced a reconnection issue where clients may not automatically reconnect to Spv servers. Has happened twice now on lbry.tv sdks. 

They would just say rpc unavailable and did not try to reconnect (maybe).

next steps:
- [x] rule out udp rate limiting (see below)
- [ ] try making reconnect timeout a bit random so many sdks that disconnected at once don't all try to reconnect at the same time

to repro:
- lower udp rate limit and see if that causes this. check udp.py for the actual rate limit. prolly over 20 clients per ip will do it
- if it does, fix would be to expose rate limit as conf var and raise it for lbrytv sdks
- if not, add more logging?

**Comment by tzarebczan** [comment]
This happened again on lbry.tv sdks today. Requires manual intervention.

**Comment by eukreign** [comment]
@tzarebczan the reconnect code already has quite a bit of logging, could you please provide the relevant logs around the time that the reconnect issues occur
