### ISSUE TITLE
Stream video in different resolutions based on bandwidth. 

### ISSUE THREAD

**Issue by namelessperson0** [lbryio/lbry-sdk#3207]
Youtube and dtube stream video in different resolutions based on client/user bandwidth. This is of paramount importance in developing countries where internet speed is low.

**Comment by tzarebczan** [comment]
Thank you for filing. There's existing issues for this and it's currently being handled outside of the SDK through our web players.

**Comment by namelessperson0** [comment]
@tzarebczan Could you point to the relevant issue/code? I am unable to find it.
