### ISSUE TITLE
Only allow uploaded videos to be seen on certain domain names

### ISSUE THREAD

**Issue by 9mido** [lbryio/lbry-sdk#3211]
I am not sure where to put this issue since it is a feature for odysee. There does not seem to be a github page just for odysee. 

Only allow uploaded videos to be seen on certain domain names when the uploaded videos are embedded into the website that has that domain name. Configure the uploaded video to not be seen on odysee publicly, but instead can only be seen on a certain domain name when embedded.

Vimeo does this. It would be great if odysee could do it as well.

If this issue does not belong here, please place it in the proper location so that it gets added.

**Comment by tzarebczan** [comment]
Thanks for the suggestion. This is not possible on an open and decentralized network as everyone will have access to the same content.

**Comment by 9mido** [comment]
@tzarebczan Good point thanks for the response.

**Comment by 9mido** [comment]
@tzarebczan PeerTube recently added this feature that is the same as what I requested here. PeerTube is also decentralized. 

https://github.com/Chocobozzz/PeerTube/issues/3773 

Maybe you could do the same exact thing by using the Referer request header?
