### ISSUE TITLE
Preference API does not support key removal

### ISSUE THREAD

**Issue by patrickkeane** [lbryio/lbry-sdk#3214]
The `lbrynet preference` API only offers `get` and `set` operations.  There is no facility to `delete` a key, once it has been `set` to some value.  Suggested API signature:

        (lbry-venv) patrick@illuminati:~$ lbrynet preference delete --help

        Delete preference key/value

        Usage:
            preference_delete (<key>) [--wallet_id=<wallet_id>]

        Options:
            --key=<key> : (str) key to be deleted
            --wallet_id=<wallet_id>   : (str) restrict operation to specific wallet

        Returns:
            (bool) true, if key exists and was removed

**Comment by patrickkeane** [comment]
If issue is accepted, here is a proposed change (+ to include unit test)

    def jsonrpc_preference_delete(self, key=None, wallet_id=None):
	"""                                                                                                  
        Delete preference                                                                                    
                                                                                                             
        Usage:                                                                                               
            preference_delete (<key>) [--wallet_id=<wallet_id>]                                              
                                                                                                             
        Options:                                                                                             
            --key=<key> : (str) key to be deleted                                                    
            --wallet_id=<wallet_id>   : (str) restrict operation to specific wallet                          
                                                                                                             
        Returns:                                                                                             
            (bool) true, if key exists and was removed                                                      
        """
        wallet = self.wallet_manager.get_wallet_or_default(wallet_id)

        if key in wallet.preferences:
            del wallet.preferences[key]
            wallet.save()
            return True

        return False

**Comment by patrickkeane** [comment]
A simple way to exercise the delete command in an pre-existing test  is to add cleanup of the preferences from (`tests/integration/blockchain/test_wallet_commands.py`) in `test_sync` is below ~ line 272:

        # Delete keys
        self.assertTrue(daemon.jsonrpc_preference_delete("one"))
        self.assertTrue(daemon.jsonrpc_preference_delete("two"))
        self.assertTrue(daemon.jsonrpc_preference_delete("conflict"))
        self.assertTrue(daemon.jsonrpc_preference_delete("another"))
        self.assertTrue(daemon.jsonrpc_preference_delete("fruit"))

        # Preferences empty
        self.assertFalse(daemon.jsonrpc_preference_get())

**Comment by eukreign** [comment]
thanks for the thorough and well put together issue but as we discussed in slack, it is not necessary to add a preference delete API since we do not actually want to allow deleting preferences (makes it harder to do proper wallet data sync'ing between devices).
