### ISSUE TITLE
Cannot get claims for channel when specifying claim_id

### ISSUE THREAD

**Issue by DispatchCommit** [lbryio/lbry-sdk#3252]
If I made a claim_search with this data: 

```json
{
    "jsonrpc": "2.0",
    "method": "claim_search",
    "params": {
        "channel": "lbry://@radiostorm#d23b22f848a5d2f62a02052748aff7ef7d156f5f",
    }
}
```

Then I get all the livestream claims for the specified channel URL.

However, if I instead pass the channel's claim_id, I don't get a list of claims:

e.g.: 

```json
{
    "jsonrpc": "2.0",
    "method": "claim_search",
    "params": {
        "claim_id": "d23b22f848a5d2f62a02052748aff7ef7d156f5f",
    }
}
```

this feels like a bug...

**Comment by tzarebczan** [comment]
You'd pass channel_id, not claim id.

**Comment by DispatchCommit** [comment]
@tzarebczan Wait that worked just fine... My bad

**Comment by DispatchCommit** [comment]
Wait `channel_id` isn't even documented.....?

https://lbry.tech/api/sdk#claim_search

`channel_ids` is, which is the closest thing, but if both `claim_id` and `claim_ids` is defined.. Then `channel_id` should be as well.

Regardless, this does what I wanted it to:

```json
{
    "jsonrpc": "2.0",
    "method": "claim_search",
    "params": {
         "channel_id": "d23b22f848a5d2f62a02052748aff7ef7d156f5f",
         "has_no_source": true
    }
}
```

The documentation is just confusing
