### ISSUE TITLE
make install doesn't install leveldb.

### ISSUE THREAD

**Issue by Kakiking** [lbryio/lbry-sdk#3281]
make install does not install leveldb and it isn't mentioned in the INSTALL.md either.
Without leveldb building plyvel fails.

**Comment by belikor** [comment]
With #3349, the required package `libleveldb-dev` is added to the list of requisites to install in Debian/Ubuntu.

**Comment by belikor** [comment]
The previous #3349 was closed because we don't need `libleveldb-dev` to compile `plyvel`.

With #3205 or #3357 this is no longer a problem; if we use `plyvel==1.2.0` pip will download a pre-compiled version that should work fine.
