### ISSUE TITLE
return release time as created time if not set

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#3304]
Currently release time is manually set by the API. Some third-party applications may not pass this, so we end up in a situation where the various apps have to look at either created time or release time. We also already use this time for sorting. 

The solution would be to return created at as the release time when release time is not set

**Comment by lyoshenka** [comment]
The SDK should not do this. It's ok to have apps look at both fields. That's better than having the SDK silently fill the release_time with the value from another field. That would be unexpected.

The SDK's job is to report what's in the claim. The apps can decide what to do with that information (it's one line of code app-side).

**Comment by jessopb** [comment]
We pass `release_time="<1640000000"` in claim search. may be related to 
https://github.com/lbryio/lbry-sdk/issues/3561
