### ISSUE TITLE
"Not enough funds to cover this transaction" when running jobs in parallel

### ISSUE THREAD

**Issue by ole-tange** [lbryio/lbry-sdk#3311]
When running jobs in parallel I get:

"Not enough funds to cover this transaction."

It is a race condition, because I do not get the error when running the exact same jobs in serial.

Looking at the Block Explorer I think the problem is that I am paying from a single input.

So when the second (parallel) transaction is run, the first has only completed charging my account, but not yet returned the remaining to my account.

If this is the root cause, a workaround would be to make sure an account is divided into smaller "coins" that can be used in parallel.

**Comment by tzarebczan** [comment]
That's most likely correct, and it's not something we'd normally recommend doing in parallel without some batching at least. You'll want to check out the account fund api examples here: https://lbry.tech/api/sdk to split up a single utxo into multiple.

You may also get better results by setting the coin_chooser: prefer_confirmed in daemon_settings.yml

**Comment by ole-tange** [comment]
But is this not a sign that the LBRY protocol is flawed, if you cannot make multiple transactions in parallel?

In my case I wasn't even trying. So it looks to me that the protocol has not been stress tested.

**Comment by eukreign** [comment]
LBRY blockchain is a fork of bitcoin; therefore, whatever scaling issues it has, we have.

As to your proposed solution, that is exactly what we do, split large TXOs into lots of little TXOs and then this will let you parallelize with each parallel process having a pool of TXOs to spend without stepping on (spending from) each other.

You can use use `account_fund` to move TXOs (within the same account). Provide the total amount you want to have split up, then the number of txos you want (internally it will take your total amount and divide it by the TXOs you requested and each TXO will be that much).

https://lbry.tech/api/sdk#account_fund
