### ISSUE TITLE
thumbnail_url not working - blank thumbnail uploaded

### ISSUE THREAD

**Issue by xylophonez** [lbryio/lbry-sdk#3320]
Something like `thumbnail_url='https://www.gentoo.org/assets/img/screenshots/gplus2-600.png'` is not uploading a thumbnail at all - it shows as blank.

It also doesn't take a file path (I guess as hinted at by 'url'), but I haven't been able to get this to work no matter what. Am I missing something?

**Comment by keikari** [comment]
Can you give a link to  the claim with the issue.
Do you mean that the URL doesn't work when trying to view it on web, or that you are trying to upload thumbnail while creating a stream. I think that the last one isn't supported.

**Comment by tzarebczan** [comment]
Please email us at hello@lbry.com with more details on what you are trying exactly and how. 

A thumbnail is not uploaded via the sdk, it's set to a URL.
