### ISSUE TITLE
help odysee

### ISSUE THREAD

**Issue by zoreu** [lbryio/lbry-sdk#3348]
Could you provide an api to list videos from a channel via get method, or put a module in python to do this function?

**Comment by belikor** [comment]
You get videos with
```
lbrynet claim search --channel=@MyChannel --stream_type=video
```

Normally this returns 1 page with 20 claims but you can make it return a page with an arbitrary number of claims. For example, to return all, you can use a very large number.
```
lbrynet claim search --channel=@MyChannel --stream_type=video --page_size=99000
```

I provide a library of functions that can be used in Python scripts, https://github.com/belikor/lbrytools

I would like to merge some useful functions into `lbrynet` but this may take a while as I need to investigate the code more.

**Comment by zoreu** [comment]
how do I put it inside a python script and list the video page links?

**Comment by belikor** [comment]
Using my code.
```py
import lbrytools

s = lbrytools.ch_search_latest("@DistroTube", number=10)
for claim in s:
    print(claim["canonical_url"])
```

The title of this issue makes no sense "help odysee". And also it's not a programming issue, so it should be closed.

**Comment by zoreu** [comment]
> Using my code.
> 
> ```python
> import lbrytools
> 
> s = lbrytools.ch_search_latest("@DistroTube", number=10)
> for claim in s:
>     print(claim["canonical_url"])
> ```
> 
> The title of this issue makes no sense "help odysee". And also it's not a programming issue, so it should be closed.

I made my addon for kodi another way
script - https://replit.com/@JoelSilva3/pluginvideovisaolibertaria#default.py
Addon for Kodi - https://github.com/zoreu/addon_visao_libertaria/raw/main/plugin.video.visaolibertaria.zip

**Comment by belikor** [comment]
The way you are doing it is not optimal.

You are querying the `lbry.tv` website. This is unnecessary as this information can be gathered from the `lbrynet` daemon running locally, which directly connects to the blockchain.

Start the `lbrynet` daemon locally.
```
lbrynet start
```

Then you can communicate through the localhost server.
```py
output = requests.post('http://localhost:5279', json=msg).json()
if "error" in output:
    return output["error"]

result = output["result"]
# inspect result for the new videos
```
