### ISSUE TITLE
Instance local cache

### ISSUE THREAD

**Issue by gizzatov** [lbryio/lbry-sdk#3375]
As I can see there this method can be used through odysee-api:
https://github.com/lbryio/lbry-sdk/blob/8304102136526e42000246a05255ae942dda5083/lbry/extras/daemon/daemon.py#L1336
I guess that means you use that method in web-application.
If we will go deeper to that part we can see that method uses local cache:
https://github.com/lbryio/lbry-sdk/blob/8304102136526e42000246a05255ae942dda5083/lbry/wallet/ledger.py#L1183
I don't realy know how you orchestrate this daemon. But I think this part could generate as many cache misses as much instances you have.
May be will be better to replace that local cache with distributed cache on redis or something else. Anyway, this code can mislead and will work only in situation with one instance.

**Comment by tzarebczan** [comment]
Thanks for looking into this and the feedback. Most user balances won't change over type, but more active accounts will. The cache is cleared when the balance updates.
