### ISSUE TITLE
pass stream types (and others?) claim params to reposted claim

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#3377]
If you pass a stream type today, you remove reposted claims. Reposted stream claims should also be returned.

Double check to make sure this is also happening for other relevant parameters that would apply to reposted claims. 

@shyba said this will require a hub resync

This is required for: https://github.com/lbryio/lbry-desktop/issues/5894

**Comment by kauffj** [comment]
please :pray:

**Comment by kauffj** [comment]
I am once again asking for your support

**Comment by kauffj** [comment]
what's holding this up?

**Comment by shyba** [comment]
It is missing a deploy of v102 to the 2 hub servers of Odysee, but it requires a resync and this takes about an hour. I will ask Jack and Tom if we should do it using a spare server or wait for the new server Jack is setting up.

ps: If someone reading this wants to develop against the fix, use spv14. It is running v102

**Comment by kauffj** [comment]
did this happen?

**Comment by kauffj** [comment]
this ticket is complete when it works for all servers, when it does, ping me @jackrobison
