### ISSUE TITLE
Finish GRPC work

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#3393]
## go hub
- [x] get build working with docker hub in under the lbry org
- [x] make a release
- [x] put release up on a production server
- [ ] add tests
- [ ] documentation (comment the .proto grpc file, readme, how to build, how to release, how to deploy, how to run in dev and prod)
- [ ] deploy to odysee

## client
- [x] make sure tests pass without fallback **[biggest unknown]**
- [x] make sure test coverage is good
- [x] run integration tests against both go hub and python hub
- [x] merge client-side PR
- [ ] run the app with the PR merged against a go hub and make sure it works (esp claim search, but also other calls)
- [ ] deploy to odysee

**Comment by shyba** [comment]
final deploy and enabling waiting for https://github.com/lbryio/hub/issues/12
