### ISSUE TITLE
drop `comment_*` apis

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#3408]
now that lbryio/lbry-desktop#5459 and lbryio/lbry-android#1131 are closed, they are no  longer used in any apps

**Comment by lyoshenka** [comment]
yes, that would be great. thank you

**Comment by cristi-zz** [comment]
On it.

**Comment by cristi-zz** [comment]
Created PR #3414.

There are some comment references left in the code, my guess is that they have nothing to do with current issue and they should be left untouched.

``jsonrpc_support_create``, ``Transaction.support()`` and there is a reference too, in ``lbry/schema/support.py``

**Comment by lyoshenka** [comment]
#3414 is merged
