### ISSUE TITLE
What's the difference between LBRY and bittorrent?

### ISSUE THREAD

**Issue by Xyncgas** [lbryio/lbry-sdk#3425]
1. Can you explain a bit why is it different than using bittorent to share content?
They are both uncensorable and decentralized and there're react front end through webtorrents that lets you watch videos online.
2. If you have to build lbry on a block chain, what value does using block chain provide us (even it's one sided & only benefitting people who are running it like is it more secure),  if it's just simply tracking who paid for what content people can also use any other coins and sell their content in any way and there's nothing stopping people for re-sharing content through bt just like lbry can't prevent someone re-upload purchased content

**Comment by belikor** [comment]
https://lbry.com/faq/different-ipfs

> Lack of discovery. BitTorrent and IPFS provide decentralized ways to access a unique piece of data or information, but they do not provide a way to discover or find what is available.

The usefulness of the blockchain is that the database of content is distributed among all people who install the blockchain node `lbrycrd`. With BitTorrent, you don't know what is available, unless you join a website that lists their torrents, there is no central database of all content.

**Comment by tzarebczan** [comment]
Thank you @belikor ! 

Another good resource is: https://lbry.tech for tech details
