### ISSUE TITLE
Is LBRY going to be censored by ISP in the future the same way ISP can censor bittorrent?

### ISSUE THREAD

**Issue by Xyncgas** [lbryio/lbry-sdk#3431]
According to : https://lbry.tech/spec#blob-exchange-protocol

LBRY is not using Bittorent, but I need help understanding whether it's practical for ISP to censor lbry protocol from continuing to operate or is it probably too much because they might be censoring all the other applications that generates similar traffic.

LBRY is advertise as a pro freedom product, and it's going to be challenged in my opinion to the people who are trying to supress it. I am also seeing countries like china with insane amount of censorships, and how tools for circumventing the Great-Fire-Wall has been using a pattern to hide their traffic in commonly used protocols (even then the CCP has been using AI to audit traffics and recognize proxy softwares), so is LBRY-protocol and LBRY Inc. going to defend our freedom and bring a internet that's more free, and I know you guys have been doing things, so I wanna know what's your determinations against some of the expected push backs from essentially everyone who's not in the interest of what you guys are doing either the ISP or the SEC or other countries which might be actively censoring it, whether it is a short term goal or a long term goal.

**Comment by belikor** [comment]
> so is LBRY-protocol and LBRY Inc. going to defend our freedom and bring a internet that's more free, 

The LBRY Inc. company doesn't have unlimited resources to fight against all ISPs, all banking regulators, all intelligence agencies, all countries, etc. It can only do what it can do, develop software to help decentralize content distribution on the Internet.

If the governments and agencies decided to "crack down" on LBRY they probably could do that, but that's similar to cracking down on BitTorrent, or cracking down on Linux, it would be extremely authoritarian, and would require a massive effort.

Obviously a goal of the project is to bring freedom to the Internet, but nobody can make any guarantees.

**Comment by Xyncgas** [comment]
As we've seen with #DropKiwiFarms one year later, isp can censor you if they want to, however the guy that's running the site fought back and managed to keep https://kiwifarms.net/ online
