### ISSUE TITLE
Is my content guaranteed to be available after publishing to LBRY? 

### ISSUE THREAD

**Issue by Xyncgas** [lbryio/lbry-sdk#3435]
LBRY hosting content I uploaded, or it's purely based on peering (/two together)

**Comment by belikor** [comment]
You cannot guarantee that LBRY Inc., the company, will host your content forever. 

Think of it like BitTorrent. If you share the file, and you have it in your system, other users can download it from you, and they can share it as well. If you delete the file from your computer, then the file can be shared as long as the rest of the peers collectively have all pieces of the file. But if everybody deletes the pieces from their computer, then nobody will be able to download it anymore. The metadata of the file will still exist in the blockchain but the actual file won't be able to be shared.

In this situation, LBRY Inc. is just a peer more in the network. They may decide to delete their copy of your file at any point, in which case it is up to you to continue sharing your file in the network.

https://lbry.com/faq/host-content
https://lbry.com/faq/content

> LBRY Inc., makes no guarantee your content will be hosted on the network. The peer-to-peer network relies on seeders to host content. If no user continues to host data - including you, it will not continue to be available on the network.

**Comment by tzarebczan** [comment]
Thank you @belikor !
