### ISSUE TITLE
Understand and/or design system on how to measure disk space available

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#3463]
And/or content availability overall

**Comment by shyba** [comment]
Some articles I found related to estimating the network size:
https://www.irjet.net/archives/V5/i12/IRJET-V5I1208.pdf
https://eli.sohl.com/2020/06/05/dht-size-estimation.html
https://www.cl.cam.ac.uk/~lw525/MLDHT/

First phase will be adding more metrics options to the DHT seed node, so an operator can use it to see data about the network partition it belongs. Then this data can be used to estimate the other partitions.

Some idea: fetch from blockchain data (hubs?) how many SD blob hashes there are for a partition and compare to how many we have seen. The ratio of existing/announced should tell how much of it is hosted initially.
