### ISSUE TITLE
Non-existent transactions in history

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#3468]
@tzarebczan will fill in details

**Comment by tzarebczan** [comment]
Recent example: 

```
{
  "items": [
    {
      "abandon_info": [],
      "claim_info": [],
      "confirmations": 0,
      "date": null,
      "fee": "-0.000676",
      "purchase_info": [],
      "support_info": [],
      "timestamp": null,
      "txid": "fc8069c189adc16a37265003613b533a0c02a837e2ab7ea48fd65f2b745bad24",
      "update_info": [
        {
          "address": "bHVgBxnqQ6ARa3xQVh3951uperyqD6rSzR",
          "amount": "0.001",
          "balance_delta": "0.0",
          "claim_id": "133911acc6fb8c26002d4e776fd65e2ccc8f3944",
          "claim_name": "@NeckeYBisweik",
          "is_spent": false,
          "nout": 0
        }
      ],
      "value": "0.0"
    }
  ],
  "page": 794,
  "page_size": 1,
  "total_items": 794,
  "total_pages": 794
}
```

This is a wallet that was having issues with conflicts and missing inputs. Later the tx  went through, but it's no where to be found. It's on a-15 connected to a hub.

**Comment by kauffj** [comment]
@shyba to update this ticket or file new ticket for any remaining work but issue is not affecting production anymore

**Comment by shyba** [comment]
With the help of @tzarebczan and @jackrobison we found a lbrycrd instance that wasn't relaying everything. One config was missing, but we weren't able to recover the transaction that caused it. So we are unsure about the real issue.

#2491 covers what we know. IMO the only thing left is to collect more information if it happens again to see if that is just 2491 again or something new.

**Comment by tzarebczan** [comment]
Closing for now, definely a rare one. We should see if #2491 is still actually possible....last I spoke to @eukreign he said this may have been fixed.
