### ISSUE TITLE
Investigate reducing transaction fee for long claim names

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#3477]

**Comment by kauffj** [comment]
https://lbryians.slack.com/archives/C9DDLUPL5/p1636730710060900?thread_ts=1635183482.012200&cid=C9DDLUPL5

**Comment by eukreign** [comment]
i changed this to 0:
https://github.com/lbryio/lbry-sdk/blob/1e00fb369d31fac980fc239b17a2834cb0631a50/lbry/wallet/ledger.py#L109
and lbrycrd still accepted the transaction

if we actually want to do this we probably need a new issue with the specific fee desired (or 0)
