### ISSUE TITLE
Remove the dependency of wallet functionality from blockchain in tests.

### ISSUE THREAD

**Issue by roylee17** [lbryio/lbry-sdk#3480]
Sub-issue of #3467 

Currently, the integration test relies on minimal wallet functionalities from blockchain, mainly for mining coins using the default account/address which then funds the wallet addresses during tests.

This was fine with `lbrycrd` which comes with builtin wallet. With migration to`lbcd`, however, the wallet functionalities are provided by a separate implementation in `lbcwallet`, which requires additional setup and teardown of `lbcwallet` just for the tests.

Among these RPCs: https://github.com/lbryio/lbry-sdk/blob/master/lbry/wallet/orchstr8/node.py#L418-L459
The `getbalance`, `sendtoaddress`, `signrawtransaction`, etc are served by `lbcwallet`

**Comment by BrannonKing** [comment]
@eukreign , how much work would it be to switch these calls to use the SDK's wallet instead?

**Comment by lyoshenka** [comment]
plan:
- when the SDK is testing it's own wallet functionality, it will set up and tear down `lbcwallet`
- in other tests, SDK will use it's own wallet

**Comment by lyoshenka** [comment]
not planning to tackle this anytime soon
