### ISSUE TITLE
Fix DHT issues discovered during network probing development

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#3494]

**Comment by shyba** [comment]
I opened issues and PRs for each case, so closing this one as it is generic.


* iterative find doesn't return everything it was asked (it is hard coded to 8) -> PR #3501
* the iterator sometimes continues even though the consumer bailed out #3504 (has reproduction script)
* Iterative find doesn't do what is on the wiki, sometimes returns too early (described on PR #3503)
