### ISSUE TITLE
Re-org crash fallout

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-sdk#3517]
- Fix underlying issue
- Examine whether past re-orgs would cause issues

**Comment by kauffj** [comment]
@lyoshenka to examine procedures/processes around production issues

**Comment by tzarebczan** [comment]
The biggest thing here is also to ensure that such an issue doesn't stop the mempool/notificaiton loop or startup of the hubs.  We should strongly log that it occurred and sacrifice data integrity issues (though these may be harder to recover from later on)

**Comment by eukreign** [comment]
might be relevant: #3520
