### ISSUE TITLE
BUG REPORT (2) : No Rate Limit + Application level DOS on Email Verifcation link 

### ISSUE THREAD

**Issue by fozi6044** [lbryio/lbry-sdk#3525]
## Description:

 I found a vulnerability on your email verification functionality. After creating an account on odysee.com then I received email verification link on my email. So I checked this functionality related to Rate limit misconfiguration. I sent 100 of resend email links and There is no rate limit applied here and after 3 to 4 requests server sending error is 503 which means server services is down during a rate limit attack. If any malicious user send a Mass email bombing attack on any victim email without his interaction then your server could be down cause of DOS attack.

## Step to Reproduce:

1) Go to create an account of victim email : https://odysee.com/$/signup
2) You received Email verification link.
3) Burp Intercept On 
4) Go to the Browser and Click on Resend link 
5) Capture request in a burp and send to the Intruder
6) Add q=0.$5$ and select Snider attack
7) Put 100 null payloads
8) Start Attack
![intruder](https://user-images.githubusercontent.com/31373835/146633518-87732e02-e231-4d99-9b30-a65228535386.png)
9) Got 43 requests in victim account.
![email](https://user-images.githubusercontent.com/31373835/146633564-4fa0e871-e944-4118-a478-30032c66e094.png)
10) You can see in attached screenshot some of request response is 503 from server.

## Remediation:

You can apply CAPTCHA on Resend email verification link.

## Impact:

An attacker will pick up a random email of any victim and make an account on odysee.com then he will send a Mass Email Bombing attack on victim email and victim would be irritated this because he dont know who is doing this malicious activity against him because its totally without victim interaction.

**Comment by tzarebczan** [comment]
Thanks for the feedback, we'll get this patched up.
