### ISSUE TITLE
SDK fails silently if P2P TCP port is in use

### ISSUE THREAD

**Issue by shyba** [lbryio/lbry-sdk#3530]
SDK silently fails to start the peer protocol server, making the whole startup fail without a clear reason.

This issue is about making that clear somehow in the logs and status.

We should consider picking a random port if no port was set by the user and 4444 is in use by something else (maybe another issue, may need discussion and input @jackrobison @lyoshenka ).

**Comment by kodxana** [comment]
Or add better error logging to not show generic error message and no other info. That would save time debuggin other users issues too.

**Comment by AlessandroSpallina** [comment]
Hi all, I added a log error to that problem, do you think it's enough?
