### ISSUE TITLE
Signing hex data that is only numbers

### ISSUE THREAD

**Issue by vertbyqb** [lbryio/lbry-sdk#3533]
When signing hexdata with `lbrynet channel sign`, hexdata that is just decimal numbers (0-9) causes an error.

## Reproduction

1. Get hexdata that is just numbers (e.g `python3 -c "print('test123'.encode().hex())"` from a shell).
2. Pass that hexdata to a `channel sign` call (`lbrynet channel sign --channel_name=@vertbyqb --hexdata=74657374313233`)

## Output

```json
{
  "code": -32500,
  "data": {
    "args": [],
    "command": "channel_sign",
    "kwargs": {
      "channel_account_id": [],
      "channel_name": "@vertbyqb",
      "hexdata": 74657374313233
    },
    "name": "TypeError",
    "traceback": [
      "Traceback (most recent call last):",
      "  File \"lbry/extras/daemon/daemon.py\", line 752, in _process_rpc_call",
      "  File \"lbry/extras/daemon/daemon.py\", line 2908, in jsonrpc_channel_sign",
      "TypeError: argument should be bytes, buffer or ASCII string, not 'int'",
      ""
    ]
  },
  "message": "argument should be bytes, buffer or ASCII string, not 'int'"
}
```

## Expected output

The hexdata should be treated as a string and should output a signature and a signing_ts.

```json
{
  "signature": "...",
  "signing_ts": "..."
}
```

## Version

```
$ lbrynet --version
lbrynet 0.106.0
```

**Comment by devbrones** [comment]
Could this not be fixed by surrounding that var with str()
