### ISSUE TITLE
Support spending timelocked transactions

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#3553]
A bunch of people bought timelocked LBC a while ago and it is going to unlock soon. We need a path for them to claim this LBC.

**Comment by kauffj** [comment]
Build SIMPLEST solution that allows this. UX can be crude and bad.

**Comment by eukreign** [comment]
@kauffj @lyoshenka by the end of the standup it seemed like this was back in @lyoshenka court, should we change the assignment?

**Comment by lyoshenka** [comment]
discussed with lex. i'll get him an example of what the data on the usb key looks like and he'll throw together an sdk command to ingest and spend it
