### ISSUE TITLE
Having `release_time` as param in `claim_search` doesn't return channel claims

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-sdk#3561]
I understood that using `release_time` as param should default to `creation_timestamp` when the claim doesn't have release_time. 

This currently also affects the LBRY desktop app in "Discovery", as most of the calls there include `release_time`. Filtering for channels returns often nothing.

**Comment by jessopb** [comment]
thank you!

**Comment by jessopb** [comment]
we have a strange choice here: 
not include release_time in a claim_search, and get scammy future claims.
include a release_time in a mixed claim_search and not get channels etc.

`claim_search` ignores `has_source` when it's included in a `claim_type="channel"`, It seems reasonable to ignore release_time too?

**Comment by jessopb** [comment]
the same is true for other RANGE params such as `duration`

**Comment by jessopb** [comment]
Solution could be 
https://github.com/lbryio/lbry-sdk/blob/c96d1d9c32337843239a8230244093fd19d79608/lbry/wallet/server/db/elasticsearch/search.py#L630 the treatment here for `has_source` could be applied to RANGE_FIELDS here https://github.com/lbryio/lbry-sdk/blob/c96d1d9c32337843239a8230244093fd19d79608/lbry/wallet/server/db/elasticsearch/search.py#L571
