### ISSUE TITLE
Deterministic channel keys "break" slightly on restart, on wallets with encryption

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-sdk#3577]
Trying to do anything with a channel with a deterministic signing_key gives `"message": "Couldn't find private key for name '@channel'."` when lbrynet is started, if wallet has encryption enabled.  
  
  
Steps to repro:
1. Have an encrypted wallet and a channel with deterministic key stuff on it.
2. Start lbrynet and unlock the wallet
3. Trying to `channel_sign` something gives this error: 
```
"traceback": [
      "Traceback (most recent call last):",
      "  File \"/home/user/git/lbry-sdk/lbry/extras/daemon/daemon.py\", line 755, in _process_rpc_call",
      "    result = await result",
      "  File \"/home/user/git/lbry-sdk/lbry/extras/daemon/daemon.py\", line 2915, in jsonrpc_channel_sign",
      "    wallet, channel_account_id, channel_id, channel_name, for_signing=True",
      "  File \"/home/user/git/lbry-sdk/lbry/extras/daemon/daemon.py\", line 5357, in get_channel_or_error",
      "    raise PrivateKeyNotFoundError(key, value)",
      "lbry.error.PrivateKeyNotFoundError: Couldn't find private key for name '@radnom'.",
      ""
    ]
  },
  "message": "Couldn't find private key for name '@radnom'."
 ```
 
 Running this command fixes it until next launch of lbrynet `./lbrynet channel create --name @sometext --bid 0.01 --preview`

**Comment by kauffj** [comment]
thanks for flagging this, we'll prioritize

**Comment by eukreign** [comment]
@keikari thanks so much for this bug report and especially the details on how to temporary fix the bug, it was very helpful in isolating the problem.

could you please test this PR to see if it fixes the problem: https://github.com/lbryio/lbry-sdk/pull/3581

**Comment by keikari** [comment]
Works now like excepted!
