### ISSUE TITLE
`content_blobs_storage_used_mb` seems to include "pending" + "finished" blobs. (Making it not to match the actual disk-usage)

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-sdk#3617]
To repro:
1. Have `save_file` disabled   
2. Check `"content_blobs_storage_used_mb":` in `status`, and the real disk-usage of blobs  
2. Run `lbrynet get 'lbry://@a#f1/ubuntu-test#e'` 
3. Run `lbrynet blob clean` to update the blob storage usage numbers in `lbrynet status`  
4. Check `"content_blobs_storage_used_mb":` again, and the real disk-usage of blobs  
5. The `"content_blobs_storage_used_mb":` instantly increased by ~2,8GB, but real disk_usage only increased the size of the sd_blob

**Comment by shyba** [comment]
Thank you very much for this clear reproduction! I was able to reproduce the issue. Opening a PR
