### ISSUE TITLE
Old channel can't sign instantly after being imported with `sync_apply` to a new SDK (needs to reconnect once for pubkey_id in channel certificate to fix itself)

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-sdk#3622]
Getting wallet that has certificates for channels from old SDK(<=0.107.2) using `sync_apply`, and importing it to newer SDK(0.109.0) using `sync_apply`, will leave a "wrong" version of pubkey_id in the certificate in the wallet. And new SDK can't find the channel certificate, until it gets updated to the pubkey_id matching the new format of public_key. (Probably)

This seems to be consistent for repro:  
1. Start lbrynet (worked on current master, and with this https://github.com/lbryio/lbry-desktop/releases/tag/v0.53.5-t109)
2. Run something like script below (just adds a single channel holding account to wallet, channel's name is channel8, made on old SDK)
3. Run `lbrynet channel sign --channel_id 82e11fe952205210afe398e970f2068a6f4ddc42 --hexdata aa`
4. See `"Couldn't find private key for id '82e11fe952205210afe398e970f2068a6f4ddc42'."`
5. The `channel_sign` will work after restart or `wallet_reconnect`.  (Also seemed to fix itself over time, but not sure why/when exactly, or maybe it was just auto reconnect)  
(Can also see that the channel certificate in wallet has different pubkey_id before the reconnect)

To run above again:  
1. Stop lbrynet
2. Remove the channel8's holding account from wallet file

Script:      
```
import requests
import json

server = "http://localhost:5279/"
sync_data = '{"data": "czo4MTkyOjE2OjE6M5jvGSSZt/i6RbwxVTQ8WxXcwRHovk/VVMrIZ+3MEXqtFoSqMqpPKUkgmNmgInEN3BQYtN9lZubKTcP2yuXTOHspO9Hnp0HrlfILE8IGv0VEiJBsKVef6raqihWZ1TzXAohzqjY43972rLyK7BXZoMmRdLt4IMtV66k3ZIKZqZcDLrKihXk7U7q72qjHZg2plDju+Ng0uN4eVelNN1lJnhBRrVg9u/WxnCx5d0rCwslutS4qKhG7Wz7xxVgwyoRNWHXgyV2v9pgI7nxzTSqaz8XVm/hk2Emc5WP08TwxQAfIqqfFeR08QU+kqqjZ/OqsiADObISmMFOT7enfgEbRUSGvbXQ/4c+GTyzMU4v8MrVLUQPzj2zQe7H2jiLtZ8T+Y6ukXwCpuAUWpD6imRkARG21XXajYrX8gYU6F4YmMfa2qka0tNFsVdGXkatLVUBJC0KCPW95RtTaFJ60yo5nVUZfl1bpRGFDS/Pjdwbtl+4A3uddxRMD8Ggf81vEzMS5wkOHDpC1iFBu0KnLd5MziBRO3JQR+Ez4ez9JoNwbUp4BamNxoR8UYG+GdyTWl0ojsGYbqkwH0Mz2J6Ux8JUJvwPlzAjTpX0QrJ2ifwagjQAGMRRTmCqm+bzY+e5nbpBstNdLOh5tX/cSKpvMuXP2QwvRmW6npqJNiQtObbKW2Q6wVH9TlfrPeC3BVQ9+kxFd"}'
call_json = {
    "method": "sync_apply",
    "params": {
        "password": "",
        "data": sync_data
    }
}

response = requests.post(server, json=call_json).json()
print(json.dumps(response, indent=4))
```

-----------------------------------------

Other details:
Using `channel_import` works without reconnect (old -> new)

**Comment by eukreign** [comment]
@keikari Is `sync_apply` called with `--blocking`?

Also, what if you just wait a little bit (a minute or two) but without restarting, does it work then?

**Comment by keikari** [comment]
It didn't seem to start to work by itself, also tried with `blocking: True`. 
But noticed the channel didn't appeared in `claim_list` either. But getting same on old SDK(I though I tested this, but guess I didn't or did something differently)   
So this is actually different minor issue than originally stated.  (Sorry)  
  
--------------------------------------------
There seems to be still some more minor, but similar(?) issue to original.  These are current steps that seemed to work:
1. Create channel on old SDK  
2. Export channel   
3. Import channel to Odysee  
4. Open LBRY desktop app that's running new SDK, with different wallet from where account was created. And sync wallet from Odysee.  (I had copy of the Odysee wallet, in state before the channel was imported. Not sure if matters.)  
5. The imported channel appears in app, but can't be used for signing. And hasn't started to work in few minutes.  
Specific error is:
```
lbrynet channel sign --channel_id 9b7d22c67b3c2e0ff2df04fb79a0c0e237f9ace0 --hexdata aa                                                                        
{
  "code": -32500,
  "data": {
    "args": [],
    "command": "channel_sign",
    "kwargs": {
      "channel_account_id": [],
      "channel_id": "9b7d22c67b3c2e0ff2df04fb79a0c0e237f9ace0",
      "hexdata": "aa"
    },
    "name": "PrivateKeyNotFoundError",
    "traceback": [
      "Traceback (most recent call last):",
      "  File \"lbry/extras/daemon/daemon.py\", line 778, in _process_rpc_call",
      "  File \"lbry/extras/daemon/daemon.py\", line 2980, in jsonrpc_channel_sign",
      "  File \"lbry/extras/daemon/daemon.py\", line 5437, in get_channel_or_error",
      "lbry.error.PrivateKeyNotFoundError: Couldn't find private key for id '9b7d22c67b3c2e0ff2df04fb79a0c0e237f9ace0'.",
      ""
    ]
  },
  "message": "Couldn't find private key for id '9b7d22c67b3c2e0ff2df04fb79a0c0e237f9ace0'."
}
```

Before above tried to sync wallet from Odysee again to local new SDK with fresh local wallet, and all channels from Odysee wallet worked.  
  
Don't have better details atm. Also no idea why it doesn't affect all channels.  

(Originally noticed some issues with this when testing on old/new Odysee instances.
1. Had imported channel to current Odysee (older SDK)
2. Synced with new SDK Odysee test instance via the default wallet sync process.
3. The imported channel couldn't sign on new SDK there.  
(Come to think of it now, I think some other channels did worked there, even at the time))

**Comment by keikari** [comment]
UPDATE:
The original issue does seem to be correct after all.  
(Got bit confused there. And for some reason my example there is broken. (Gives `Channel not found error` like the account holding channel wasn't in the wallet. Not sure why. Maybe made mistake there, though I think I tested it after posting at least once).)  

At the moment pretty sure that these steps work for repro. 

Do this on old SDK (<=107.2)
1. Have some wallet loaded that has channels and their keys
2. Run `sync_apply` to export the wallet
3. Stop SDK
4. Add some wallet name that doesn't exists as the only wallet in daemon_settings.yml (make SDK create a fresh wallet. Doesn't have to be a fresh one, but makes easier to see the issue)  
  
Do this on new SDK (109)
5. Start SDK
5. `sync_apply` the exported wallet from before ( 
6. Try to sign something with any of the channels  
7. See `Couldn't find private key' errors
8. The channel_sign will work after restart or `wallet_reconnect`. 

`"blocking": True` doesn't seem to make difference (was originally called without that)   
Doesn't fix itself in minutes (don't know if it fixes itself at all)

**Comment by eukreign** [comment]
But as soon as you restart SDK it works again?

So, there is something that restart fixes in the wallet they simply sunc_apply does not, hmm.

**Comment by keikari** [comment]
Yeah, restart or just a `wallet_reconnect` fixes it instantly.
