### ISSUE TITLE
Sometimes `lbrynet get` reponse has blank `suggested_file_name` and incorrect `"mime_type": "application/octet-stream"`

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-sdk#3681]
Seems to happen for all recent manual uploads on Odysee. (Not seeing with published livestreams nor synced videos, nor with the uploads from the LBRY app)

Some examples: 
`lbry://@EAKoetting:1/black-magicians-handbook-conner-kendall:a`
`lbry://@Channel:c7/20220929_231654:d`

Both have these in the output of `lbrynet get`  
```
"mime_type": "application/octet-stream", 
"stream_name": "",
"suggested_file_name": "",
```

`metadata.source` in the output does have the expected values
```
"media_type": "video/mp4",
"name": "20220929_231654.mp4",
```

**Comment by tzarebczan** [comment]
We recently started using stream create with manual SD hash and metadata, and these seem to be the ones that break. All relevant fields should already be there.
