### ISSUE TITLE
Wallet export/import

### ISSUE THREAD

**Issue by zedeus** [lbryio/lbry-sdk#773]
Story: As a user I want to be able to backup/export my wallet so I can make sure I don't lose it, or use it on another device instead, but currently this process is confusing.

Currently the only way to backup the wallet is by copying the lbryum wallet files (or just the whole directory), which for the layman can be confusing and quite inconvenient. Having an export/import feature built-in to lbry (probably lbryum), with some buttons in the LBRY app, would make this process far easier, less prone to error, and very convenient.

**Comment by tzarebczan** [comment]
If we want to expand this a bit, allow export of content data also, which would follow something like the clean install process (I'll send it to). This would allow users to bring over downloaded content, configuration files, data files and blobs.

**Comment by tzarebczan** [comment]
Can we make it more apparent to the user that they should backup their wallet? Unless they read through the FAQ, they may not know.

**Comment by kauffj** [comment]
We're not going to start on this until encrypt/decrypt is merged as it will affect this process. If you want to create a FAQ article and add a help link in the interim, we can do that. A help link would be added to this file: https://github.com/lbryio/lbry-app/blob/master/ui/js/page/wallet/view.jsx

**Comment by alyssaoc** [comment]
@eukreign was this addressed in the new wallet?

**Comment by eukreign** [comment]
Needs to be implemented in new wallet.

**Comment by eukreign** [comment]
Wallet is already in a file which can be backed up, moved around, etc. We don't plan to do anything additional here.
