### ISSUE TITLE
Add support to abandon multiple claims/txid+nouts at once

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#941]
## The Issue
The [claim abandon](https://lbryio.github.io/lbry/cli/#claim_abandon) command only takes a single claim or txid/nout currently.  Going forward, it may be beneficial in some cases to abandon multiple claims in a single transaction.  One such use case would be where a user is deleting their channel and all associated claims. This ticket is to add batch support to abandoning claims or change the daemon to support https://github.com/lbryio/lbry-app/issues/625#issuecomment-336473481. 

The daemon should still be responsible for making sure the claims are allowed to be abandoned - i.e. don't allow abandoning of a channel if there are still published claims under it and provide a response to any supports (tips + self supports) that are part of a claim being abandoned so that the user can abandon all in 1 shot.

**Comment by eukreign** [comment]
Valid issue and still needs to be implemented. Shouldn't be hard to do with the new wallet.

**Comment by tzarebczan** [comment]
@eukreign - we got close with support abandon on this one. We now have the ability to abandon all supports (tips). So we just need an additional parameter on claim/channel abandon where you'd then call support abandon (without any keep value). Not sure how common abandoning a claim with supports is, but it doesn't make sense to leave the supports there, if they do exist. 

Return all the funds to the user's wallet in a single tx (or split up into appropriately sized txs - i.e. let's say I have 100K tips on a single claim - that may be too large for a single tx. Does torba already handle that? If not, it shouldn't it be done at that level?
